  CREATE TABLE "B_SL_C_PYTANIE" 
   (	"ID_PK_B_SL_C_PYTANIE" NUMBER DEFAULT "DAW"."DAW_SEQ_ID_PK_B_SL_C_PYTANIE_PK"."NEXTVAL" NOT NULL ENABLE, 
	"B_SL_C_PYTANIE_TRESC" VARCHAR2(4000 CHAR), 
	"B_SL_C_PYTANIE_WAGA" NUMBER, 
	"B_SL_C_PYTANIE_KOLEJNOSC" NUMBER, 
	"B_SL_C_PYTANIE_POMOC" CLOB, 
	"ID_FK_B_SL_C_PYTANIE_DZIEDZINA" NUMBER(10,0), 
	 CONSTRAINT "B_SL_C_PYTANIE_PK" PRIMARY KEY ("ID_PK_B_SL_C_PYTANIE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_ANKIETA" 
   (	"ID_PK_B_ANKIETA" NUMBER(11,0) DEFAULT DAW.DAW_SEQ_B_C_ANAKIETA_PK.NEXTVAL, 
	"ID_FK_B_AUDYT" NUMBER, 
	"ID_FK_B_KONTROLA" NUMBER NOT NULL ENABLE, 
	"ID_FK_B_SL_C_PYTANIE" NUMBER, 
	"B_SL_C_PYTANIE_WAGA" NUMBER, 
	"ID_FK_B_SL_C_PYTANIE_DZIEDZINA" NUMBER(10,0) NOT NULL ENABLE, 
	"SHORT_DESCRIPTION_FR_" VARCHAR2(4000), 
	"REFERENCE_ID" VARCHAR2(50), 
	"B_ANKIETA_ODPOWIEDZ" VARCHAR2(20), 
	"B_ANKIETA_OCENA_WAZONA_LICZ" NUMBER, 
	"B_ANKIETA_KOMENTARZ" VARCHAR2(4000), 
	"B_ANKIETA_LINK_DOKUMENTACJA" VARCHAR2(1000), 
	"DATA_OSTATNIEJ_KONTROLI_NA_MOMENT_AUDYTU" DATE, 
	 CONSTRAINT "B_ANKIETA_CON" PRIMARY KEY ("ID_PK_B_ANKIETA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_AUDYT" 
   (	"ID_PK_B_AUDYT" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"B_AUDYT_NUMER_AUDYTU" VARCHAR2(40 CHAR), 
	"STATUS_AUDYTU" VARCHAR2(20) DEFAULT 'Otwarty' NOT NULL ENABLE, 
	"SZEF_MISJI_LOGIN" VARCHAR2(100), 
	"AUDYTORZY_LOGINY" VARCHAR2(4000), 
	"DATA_UTWORZENIA" DATE DEFAULT SYSDATE, 
	"DATA_ZAMROZENIA" DATE, 
	"DATA_ZAKONCZENIA" DATE, 
	"ZAMROZIL_LOGIN" VARCHAR2(100), 
	"ZAKONCZYL_LOGIN" VARCHAR2(100), 
	 CONSTRAINT "B_AUDYT_PK" PRIMARY KEY ("ID_PK_B_AUDYT")
  USING INDEX  ENABLE, 
	 CONSTRAINT "B_AUDYT_STATUS_CHK" CHECK (STATUS_AUDYTU IN ('Otwarty', 'Zamrozony', 'Zakonczony')) ENABLE
   ) ;

  CREATE TABLE "B_AUDYT_KONTROLA" 
   (	"ID_PK_B_AUDYT_KONTROLA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_FK_B_AUDYT" NUMBER NOT NULL ENABLE, 
	"ID_FK_B_KONTROLA" NUMBER NOT NULL ENABLE, 
	"DODAL_LOGIN" VARCHAR2(100) NOT NULL ENABLE, 
	"DATA_DODANIA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "B_AUDYT_KONTROLA_PK" PRIMARY KEY ("ID_PK_B_AUDYT_KONTROLA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "B_AUDYT_KONTROLA_UNQ" UNIQUE ("ID_FK_B_AUDYT", "ID_FK_B_KONTROLA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_IMPORT_LOG" 
   (	"ID_PK_B_IMPORT_LOG" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DATA_IMPORTU" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UZYTKOWNIK" VARCHAR2(100) NOT NULL ENABLE, 
	"NAZWA_PLIKU" VARCHAR2(500), 
	"LICZBA_WCZYTANYCH" NUMBER DEFAULT 0, 
	"LICZBA_DODANYCH" NUMBER DEFAULT 0, 
	"LICZBA_ZMODYFIKOWANYCH" NUMBER DEFAULT 0, 
	"LICZBA_DEZAKTYWOWANYCH" NUMBER DEFAULT 0, 
	"LICZBA_BEZ_ZMIAN" NUMBER DEFAULT 0, 
	"LICZBA_BLEDOW" NUMBER DEFAULT 0, 
	"STATUS_IMPORTU" VARCHAR2(20) DEFAULT 'W_TOKU', 
	"KOMUNIKAT_BLEDU" VARCHAR2(4000), 
	 CONSTRAINT "B_IMPORT_LOG_PK" PRIMARY KEY ("ID_PK_B_IMPORT_LOG")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_KONTROLA" 
   (	"ID_PK_B_KONTROLA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"REFERENCE_ID" VARCHAR2(50), 
	"DATA_OSTATNIEJ_KONTROLI" DATE, 
	"DATA_PIERWSZEJ_KONTROLI" DATE, 
	"LICZBA_WYKONANYCH_KONTROLI" NUMBER, 
	"STATUS" VARCHAR2(50), 
	"CONTROL_LEVEL" VARCHAR2(50), 
	"DESCRIPTION_FR_" VARCHAR2(4000), 
	"DESCRIPTION_EN_" VARCHAR2(4000), 
	"SHORT_DESCRIPTION_FR_" VARCHAR2(4000), 
	"SHORT_DESCRIPTION_EN_" VARCHAR2(4000), 
	"DEFINITION_FR_" VARCHAR2(4000), 
	"DEFINITION_EN_" VARCHAR2(4000), 
	"OBJECTIVE_FR_" VARCHAR2(4000), 
	"OBJECTIVE_EN_" VARCHAR2(4000), 
	"DOMAIN_PROCESS" VARCHAR2(255), 
	"RISKS" VARCHAR2(4000), 
	"CONTROL_GROUP" VARCHAR2(255), 
	"DATA_DEZAKTYWACJI" DATE, 
	"ID_FK_B_IMPORT_LOG" NUMBER, 
	 PRIMARY KEY ("ID_PK_B_KONTROLA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_KONTROLA_HIST" 
   (	"ID_PK_B_KONTROLA_HIST" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_FK_B_KONTROLA" NUMBER NOT NULL ENABLE, 
	"ID_FK_B_IMPORT_LOG" NUMBER NOT NULL ENABLE, 
	"DATA_ARCHIWIZACJI" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UZYTKOWNIK_ZMIANY" VARCHAR2(100) NOT NULL ENABLE, 
	"REFERENCE_ID" VARCHAR2(50), 
	"STATUS" VARCHAR2(50), 
	"CONTROL_LEVEL" VARCHAR2(50), 
	"DESCRIPTION_FR_" VARCHAR2(4000), 
	"DESCRIPTION_EN_" VARCHAR2(4000), 
	"SHORT_DESCRIPTION_FR_" VARCHAR2(4000), 
	"SHORT_DESCRIPTION_EN_" VARCHAR2(4000), 
	"DEFINITION_FR_" VARCHAR2(4000), 
	"DEFINITION_EN_" VARCHAR2(4000), 
	"OBJECTIVE_FR_" VARCHAR2(4000), 
	"OBJECTIVE_EN_" VARCHAR2(4000), 
	"DOMAIN_PROCESS" VARCHAR2(255), 
	"RISKS" VARCHAR2(4000), 
	"CONTROL_GROUP" VARCHAR2(255), 
	 CONSTRAINT "B_KONTROLA_HIST_PK" PRIMARY KEY ("ID_PK_B_KONTROLA_HIST")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_KONTROLA_IMPORT" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_SESJI_IMPORTU" NUMBER NOT NULL ENABLE, 
	"REFERENCE_ID" VARCHAR2(50), 
	"STATUS" VARCHAR2(50), 
	"CONTROL_LEVEL" VARCHAR2(50), 
	"DESCRIPTION_FR_" VARCHAR2(4000), 
	"DESCRIPTION_EN_" VARCHAR2(4000), 
	"SHORT_DESCRIPTION_FR_" VARCHAR2(4000), 
	"SHORT_DESCRIPTION_EN_" VARCHAR2(4000), 
	"DEFINITION_FR_" VARCHAR2(4000), 
	"DEFINITION_EN_" VARCHAR2(4000), 
	"OBJECTIVE_FR_" VARCHAR2(4000), 
	"OBJECTIVE_EN_" VARCHAR2(4000), 
	"DOMAIN_PROCESS" VARCHAR2(255), 
	"RISKS" VARCHAR2(4000), 
	"CONTROL_GROUP" VARCHAR2(255), 
	"BLAD_WALIDACJI" VARCHAR2(4000), 
	"STATUS_WIERSZA" VARCHAR2(20) DEFAULT 'NOWY', 
	 CONSTRAINT "B_KONTROLA_IMPORT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_KONTROLA_TMP" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_KONTROLA" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_OCENA" 
   (	"ID_FK_B_AUDYT" NUMBER NOT NULL ENABLE, 
	"ID_FK_B_KONTROLA" NUMBER NOT NULL ENABLE, 
	"B_SL_C_PYTANIE_DZIEDZINA_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ID_PK_B_OCENA" NUMBER(38,0) DEFAULT DAW.DAW_SEQ_B_C_ODPOWIEDZ_PK.NEXTVAL NOT NULL ENABLE, 
	"B_OCENA_LICZONA" NUMBER(15,2), 
	"B_OCENA_NADPISANA" NUMBER, 
	"B_OCENA_CZY_NADPISANA" NUMBER DEFAULT 0, 
	"B_OCENA_PRZELAMANA_UZASADNIENIE" VARCHAR2(4000), 
	 CONSTRAINT "B_ODPOWIEDZ_PK" PRIMARY KEY ("ID_PK_B_OCENA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "B_SL_C_PYTANIE_DZIEDZINA" 
   (	"ID_PK_B_C_PYTANIE_DZIEDZINA" NUMBER(7,0) DEFAULT "DAW"."DAW_SEQ_B_SL_C_PYTANIE_DZIEDZINA_PK"."NEXTVAL", 
	"B_SL_C_PYTANIE_DZIEDZINA_TEKST" VARCHAR2(100), 
	 CONSTRAINT "B_SL_C_PYTANIE_DZIEDZINA_PK" PRIMARY KEY ("ID_PK_B_C_PYTANIE_DZIEDZINA")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "B_ANKIETA" ADD CONSTRAINT "B_ANKIETA_B_AUDYT_FK" FOREIGN KEY ("ID_FK_B_AUDYT")
	  REFERENCES "B_AUDYT" ("ID_PK_B_AUDYT") ENABLE;
  ALTER TABLE "B_ANKIETA" ADD CONSTRAINT "B_ANKIETA_B_KONTROLA_FK" FOREIGN KEY ("ID_FK_B_KONTROLA")
	  REFERENCES "B_KONTROLA" ("ID_PK_B_KONTROLA") ENABLE;
  ALTER TABLE "B_ANKIETA" ADD CONSTRAINT "B_ANKIETA_B_SL_C_PYTANIE_FK" FOREIGN KEY ("ID_FK_B_SL_C_PYTANIE")
	  REFERENCES "B_SL_C_PYTANIE" ("ID_PK_B_SL_C_PYTANIE") ENABLE;
  ALTER TABLE "B_ANKIETA" ADD CONSTRAINT "B_ANKIETA_B_SL_C_PYTANIE_DZIEDZINA_FK" FOREIGN KEY ("ID_FK_B_SL_C_PYTANIE_DZIEDZINA")
	  REFERENCES "B_SL_C_PYTANIE_DZIEDZINA" ("ID_PK_B_C_PYTANIE_DZIEDZINA") ENABLE;

   COMMENT ON COLUMN "B_AUDYT"."STATUS_AUDYTU" IS 'Status audytu: Otwarty=edycja mozliwa, Zamrozony=brak zmian listy kontroli, Zakonczony=brak jakichkolwiek zmian';
   COMMENT ON COLUMN "B_AUDYT"."SZEF_MISJI_LOGIN" IS 'Login LDAP (APP_USER) szefa misji – zapisywany przy tworzeniu rekordu, tylko on moze zamrozic/zakonczyc audyt';
   COMMENT ON COLUMN "B_AUDYT"."AUDYTORZY_LOGINY" IS 'Loginy LDAP audytorow uprawnionych do edycji, oddzielone przecinkiem (np. JAN.KOWALSKI,ANNA.NOWAK)';
   COMMENT ON COLUMN "B_AUDYT"."DATA_ZAMROZENIA" IS 'Data zamrozenia listy kontroli przez szefa misji';
   COMMENT ON COLUMN "B_AUDYT"."DATA_ZAKONCZENIA" IS 'Data zakonczenia audytu przez szefa misji (brak dalszych zmian)';
   COMMENT ON TABLE "B_AUDYT"  IS 'Tabela audytow. Cykl zycia statusu: Otwarty -> Zamrozony -> Zakonczony.';

  ALTER TABLE "B_AUDYT_KONTROLA" ADD CONSTRAINT "B_AUDYT_KONTROLA_FK1" FOREIGN KEY ("ID_FK_B_AUDYT")
	  REFERENCES "B_AUDYT" ("ID_PK_B_AUDYT") ENABLE;
  ALTER TABLE "B_AUDYT_KONTROLA" ADD CONSTRAINT "B_AUDYT_KONTROLA_FK2" FOREIGN KEY ("ID_FK_B_KONTROLA")
	  REFERENCES "B_KONTROLA" ("ID_PK_B_KONTROLA") ENABLE;

  CREATE INDEX "B_AUDYT_KONTROLA_IDX1" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT") 
  ;

  CREATE INDEX "B_AUDYT_KONTROLA_IDX2" ON "B_AUDYT_KONTROLA" ("ID_FK_B_KONTROLA") 
  ;

   COMMENT ON COLUMN "B_AUDYT_KONTROLA"."DODAL_LOGIN" IS 'Login LDAP uzytkownika, ktory dodal kontrole do audytu';
   COMMENT ON TABLE "B_AUDYT_KONTROLA"  IS 'Lista kontroli przypisanych do audytu. INSERT/DELETE mozliwy tylko gdy STATUS_AUDYTU=Otwarty (wymuszane przez PKG_AUDYT).';

   COMMENT ON COLUMN "B_IMPORT_LOG"."UZYTKOWNIK" IS 'Login LDAP uzytkownika APEX (APP_USER), ktory uruchomil import';
   COMMENT ON COLUMN "B_IMPORT_LOG"."STATUS_IMPORTU" IS 'W_TOKU=import trwa, ZAKONCZONE=sukces, BLAD_KRYTYCZNY=nieobsluzony wyjatek';
   COMMENT ON TABLE "B_IMPORT_LOG"  IS 'Log kazdego uruchomienia importu kontroli z Excela. Jeden rekord = jeden import.';

   COMMENT ON COLUMN "B_KONTROLA"."DATA_DEZAKTYWACJI" IS 'Data ustawienia STATUS=Deactive (brak rekordu w pliku importu). NULL gdy aktywny.';
   COMMENT ON COLUMN "B_KONTROLA"."ID_FK_B_IMPORT_LOG" IS 'Ostatni import, ktory modyfikowal ten rekord (FK do B_IMPORT_LOG)';
   COMMENT ON TABLE "B_KONTROLA"  IS 'WITH kontrole AS (
SELECT
	a.REFERENCE AS REFERENCE_id,
	max(a.AS_OF_DATE) AS data_ostatniej_kontroli,
	min(a.AS_OF_DATE) AS data_pierwszej_kontroli,
	count(1) AS liczba_wykonanych_kontroli
FROM
	ZKW_GRP.SCOPE_DEFINITION_2024 a
GROUP BY
	a.REFERENCE)
SELECT
	DISTINCT aa.*,
b.STATUS,
b.CONTROL_LEVEL ,
b.DESCRIPTION____FR_ ,
b.DESCRIPTION____EN_ ,
b.SHORT_DESCRIPTION____FR_,
b.SHORT_DESCRIPTION____EN_,
b.DEFINITION____FR_,
b.DEFINITION____EN_,
b.OBJECTIVE____FR_,
b.OBJECTIVE____EN_,
b.DOMAIN_PROCESS,
b.RISKS,
b.CONTROL_GROUP
FROM
	kontrole aa
JOIN ZKW_GRP.SCOPE_DEFINITION_2024 b ON
	aa.REFERENCE_id = b.REFERENCE
	AND aa.data_ostatniej_kontroli = b.AS_OF_DATE';

  ALTER TABLE "B_KONTROLA_HIST" ADD CONSTRAINT "B_KONTROLA_HIST_FK" FOREIGN KEY ("ID_FK_B_KONTROLA")
	  REFERENCES "B_KONTROLA" ("ID_PK_B_KONTROLA") ENABLE;

  CREATE INDEX "B_KONTROLA_HIST_IDX1" ON "B_KONTROLA_HIST" ("ID_FK_B_KONTROLA") 
  ;

  CREATE INDEX "B_KONTROLA_HIST_IDX2" ON "B_KONTROLA_HIST" ("ID_FK_B_IMPORT_LOG") 
  ;

   COMMENT ON COLUMN "B_KONTROLA_HIST"."ID_FK_B_KONTROLA" IS 'Klucz obcy do B_KONTROLA – nie zmienia sie przy aktualizacjach';
   COMMENT ON COLUMN "B_KONTROLA_HIST"."ID_FK_B_IMPORT_LOG" IS 'Import, ktory spowodowal zmiane';
   COMMENT ON COLUMN "B_KONTROLA_HIST"."DATA_ARCHIWIZACJI" IS 'Kiedy stara wersja zostala zarchiwizowana (= moment importu)';
   COMMENT ON TABLE "B_KONTROLA_HIST"  IS 'Historia zmian tabeli B_KONTROLA. Kazda aktualizacja importem zapisuje tu poprzednia wersje rekordu.';

  CREATE INDEX "B_KONTROLA_IMPORT_IDX1" ON "B_KONTROLA_IMPORT" ("ID_SESJI_IMPORTU", "STATUS_WIERSZA") 
  ;

   COMMENT ON COLUMN "B_KONTROLA_IMPORT"."ID_SESJI_IMPORTU" IS 'Laczy wiersze z konkretna sesja importu (B_IMPORT_LOG.ID_PK_B_IMPORT_LOG)';
   COMMENT ON COLUMN "B_KONTROLA_IMPORT"."STATUS_WIERSZA" IS 'NOWY=oczekuje na przetworzenie, OK=przetworzony, BLAD=blad walidacji';
   COMMENT ON TABLE "B_KONTROLA_IMPORT"  IS 'Tabela stagingowa do importu kontroli z pliku Excel przez APEX. Czyszczona po kazdym zakonczonym imporcie.';

   COMMENT ON TABLE "B_KONTROLA_TMP"  IS 'tabela tymczasowa z ID kontroli w audycie IT - tabela do skasowania w przyszłości';

  ALTER TABLE "B_OCENA" ADD CONSTRAINT "B_OCENA_B_AUDYT_FK" FOREIGN KEY ("ID_FK_B_AUDYT")
	  REFERENCES "B_AUDYT" ("ID_PK_B_AUDYT") ENABLE;
  ALTER TABLE "B_OCENA" ADD CONSTRAINT "B_OCENA_B_KONTROLA_FK" FOREIGN KEY ("ID_FK_B_KONTROLA")
	  REFERENCES "B_KONTROLA" ("ID_PK_B_KONTROLA") ENABLE;

   COMMENT ON TABLE "B_OCENA"  IS 'CREATE TABLE B_ODPOWIEDZ AS 	
SELECT
	DISTINCT 
	ID_FK_B_AUDYT,
	ID_FK_B_KONTROLA,
	B_SL_C_PYTANIE_DZIEDZINA_ID
FROM
	B_ANKIETA';

  ALTER TABLE "B_SL_C_PYTANIE" ADD CONSTRAINT "B_SL_C_PYTANIE_B_SL_C_PYTANIE_DZIEDZINA_FK" FOREIGN KEY ("ID_FK_B_SL_C_PYTANIE_DZIEDZINA")
	  REFERENCES "B_SL_C_PYTANIE_DZIEDZINA" ("ID_PK_B_C_PYTANIE_DZIEDZINA") ENABLE;

   COMMENT ON TABLE "B_SL_C_PYTANIE"  IS 'Słownik pytań do zakładki C. Ocena kontroli';

   COMMENT ON TABLE "B_V_AUDYT_KONTROLE"  IS 'Widok: kontrole przypisane do audytow z pelnymi danymi. Zrodlo danych dla stron APEX audytu.';

   COMMENT ON TABLE "B_V_IMPORT_STATYSTYKI"  IS 'Widok: historia importow kontroli z podsumowaniem statystyk. Zrodlo danych dla strony logow importu w APEX.';


































  CREATE INDEX "B_AUDYT_KONTROLA_IDX1" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT") 
  ;

  CREATE INDEX "B_AUDYT_KONTROLA_IDX2" ON "B_AUDYT_KONTROLA" ("ID_FK_B_KONTROLA") 
  ;

  CREATE UNIQUE INDEX "B_AUDYT_KONTROLA_PK" ON "B_AUDYT_KONTROLA" ("ID_PK_B_AUDYT_KONTROLA") 
  ;

  CREATE UNIQUE INDEX "B_AUDYT_KONTROLA_UNQ" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT", "ID_FK_B_KONTROLA") 
  ;

  CREATE UNIQUE INDEX "B_AUDYT_PK" ON "B_AUDYT" ("ID_PK_B_AUDYT") 
  ;

  CREATE UNIQUE INDEX "B_IMPORT_LOG_PK" ON "B_IMPORT_LOG" ("ID_PK_B_IMPORT_LOG") 
  ;

  CREATE INDEX "B_KONTROLA_HIST_IDX1" ON "B_KONTROLA_HIST" ("ID_FK_B_KONTROLA") 
  ;

  CREATE INDEX "B_KONTROLA_HIST_IDX2" ON "B_KONTROLA_HIST" ("ID_FK_B_IMPORT_LOG") 
  ;

  CREATE UNIQUE INDEX "B_KONTROLA_HIST_PK" ON "B_KONTROLA_HIST" ("ID_PK_B_KONTROLA_HIST") 
  ;

  CREATE INDEX "B_KONTROLA_IMPORT_IDX1" ON "B_KONTROLA_IMPORT" ("ID_SESJI_IMPORTU", "STATUS_WIERSZA") 
  ;

  CREATE UNIQUE INDEX "B_KONTROLA_IMPORT_PK" ON "B_KONTROLA_IMPORT" ("ID") 
  ;

  CREATE UNIQUE INDEX "B_ODPOWIEDZ_PK" ON "B_OCENA" ("ID_PK_B_OCENA") 
  ;

  CREATE UNIQUE INDEX "B_SL_C_PYTANIE_DZIEDZINA_PK" ON "B_SL_C_PYTANIE_DZIEDZINA" ("ID_PK_B_C_PYTANIE_DZIEDZINA") 
  ;

  CREATE UNIQUE INDEX "B_SL_C_PYTANIE_PK" ON "B_SL_C_PYTANIE" ("ID_PK_B_SL_C_PYTANIE") 
  ;














create or replace PACKAGE PKG_AUDYT AS

    -- Stale statusow audytu
    C_STATUS_OTWARTY    CONSTANT VARCHAR2(20) := 'Otwarty';
    C_STATUS_ZAMROZONY  CONSTANT VARCHAR2(20) := 'Zamrozony';
    C_STATUS_ZAKONCZONY CONSTANT VARCHAR2(20) := 'Zakonczony';

    -- Tworzenie nowego audytu
    -- p_uzytkownik automatycznie staje sie szefem misji
    PROCEDURE UTWORZ_AUDYT (
        p_numer_audytu  IN  VARCHAR2,
        p_uzytkownik    IN  VARCHAR2,
        p_id_audytu     OUT NUMBER
    );

    -- Dodanie kontroli do listy audytu (tylko STATUS=Otwarty, szef lub audytor)
    PROCEDURE DODAJ_KONTROLE (
        p_id_audytu     IN NUMBER,
        p_id_kontrola   IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    );

    -- Usuniecie kontroli z listy audytu (tylko STATUS=Otwarty, szef lub audytor)
    PROCEDURE USUN_KONTROLE (
        p_id_audytu     IN NUMBER,
        p_id_kontrola   IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    );

    -- Zamrozenie audytu – blokuje dodawanie/usuwanie kontroli (tylko szef misji)
    PROCEDURE ZAMROZ_AUDYT (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    );

    -- Zakonczenie audytu – blokuje wszelkie zmiany (tylko szef misji)
    PROCEDURE ZAKONCZ_AUDYT (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    );

    -- Sprawdza role uzytkownika: zwraca 'SZEF' / 'AUDYTOR' / 'BRAK'
    FUNCTION SPRAWDZ_UPRAWNIENIA (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) RETURN VARCHAR2;

    -- Czy uzytkownik moze edytowac dane audytu? (szef lub audytor + nie Zakonczony)
    FUNCTION MOZE_EDYTOWAC (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) RETURN BOOLEAN;

END PKG_AUDYT;
/
create or replace PACKAGE PKG_IMPORT_KONTROLI AS
    -- Glowna procedura importu – wywolywana z przycisku na stronie APEX
    -- p_id_sesji_importu : ID sesji z tabeli stagingowej
    -- p_nazwa_pliku      : oryginalna nazwa wgranego pliku (do logu)
    -- p_uzytkownik       : APP_USER z APEX (login LDAP)
    -- p_id_log           : OUT – ID rekordu w B_IMPORT_LOG (do wyswietlenia statystyk)
    PROCEDURE WYKONAJ_IMPORT (
        p_id_sesji_importu  IN  NUMBER,
        p_nazwa_pliku       IN  VARCHAR2,
        p_uzytkownik        IN  VARCHAR2,
        p_id_log            OUT NUMBER
    );
    -- Walidacja wierszy stagingu przed wlasciwym importem
    PROCEDURE WALIDUJ_STAGING (
        p_id_sesji_importu  IN NUMBER,
        p_id_log            IN NUMBER
    );
    -- Funkcja pomocnicza: czy dwie wartosci VARCHAR2 sa rozne (z obsługa NULL)
    FUNCTION CZY_ROZNE (
        p_stara IN VARCHAR2,
        p_nowa  IN VARCHAR2
    ) RETURN BOOLEAN;
END PKG_IMPORT_KONTROLI;
/



















































   CREATE SEQUENCE  "DAW_SEQ_B_C_ANAKIETA_PK"  MINVALUE 0 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1203 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "DAW_SEQ_B_C_ODPOWIEDZ_PK"  MINVALUE 0 MAXVALUE 9999999 INCREMENT BY 1 START WITH 200 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "DAW_SEQ_B_SL_C_PYTANIE_DZIEDZINA_PK"  MINVALUE 0 MAXVALUE 9999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "DAW_SEQ_ID_PK_B_SL_C_PYTANIE_PK"  MINVALUE 0 MAXVALUE 999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;



































  CREATE OR REPLACE FORCE EDITIONABLE VIEW "B_V_AUDYT_KONTROLE" ("ID_PK_B_AUDYT_KONTROLA", "ID_FK_B_AUDYT", "ID_FK_B_KONTROLA", "DODAL_LOGIN", "DATA_DODANIA", "REFERENCE_ID", "STATUS_KONTROLI", "CONTROL_LEVEL", "SHORT_DESCRIPTION_FR_", "SHORT_DESCRIPTION_EN_", "DESCRIPTION_FR_", "DESCRIPTION_EN_", "DOMAIN_PROCESS", "CONTROL_GROUP", "RISKS", "B_AUDYT_NUMER_AUDYTU", "STATUS_AUDYTU", "SZEF_MISJI_LOGIN", "AUDYTORZY_LOGINY") AS 
  SELECT
    ak.ID_PK_B_AUDYT_KONTROLA,
    ak.ID_FK_B_AUDYT,
    ak.ID_FK_B_KONTROLA,
    ak.DODAL_LOGIN,
    ak.DATA_DODANIA,
    k.REFERENCE_ID,
    k.STATUS                AS STATUS_KONTROLI,
    k.CONTROL_LEVEL,
    k.SHORT_DESCRIPTION_FR_,
    k.SHORT_DESCRIPTION_EN_,
    k.DESCRIPTION_FR_,
    k.DESCRIPTION_EN_,
    k.DOMAIN_PROCESS,
    k.CONTROL_GROUP,
    k.RISKS,
    a.B_AUDYT_NUMER_AUDYTU,
    a.STATUS_AUDYTU,
    a.SZEF_MISJI_LOGIN,
    a.AUDYTORZY_LOGINY
FROM
    B_AUDYT_KONTROLA    ak
    JOIN B_KONTROLA     k  ON k.ID_PK_B_KONTROLA = ak.ID_FK_B_KONTROLA
    JOIN B_AUDYT        a  ON a.ID_PK_B_AUDYT     = ak.ID_FK_B_AUDYT;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "B_V_IMPORT_STATYSTYKI" ("ID_PK_B_IMPORT_LOG", "DATA_IMPORTU", "UZYTKOWNIK", "NAZWA_PLIKU", "LICZBA_WCZYTANYCH", "LICZBA_DODANYCH", "LICZBA_ZMODYFIKOWANYCH", "LICZBA_DEZAKTYWOWANYCH", "LICZBA_BEZ_ZMIAN", "LICZBA_BLEDOW", "STATUS_IMPORTU", "KOMUNIKAT_BLEDU", "PODSUMOWANIE") AS 
  SELECT
    il.ID_PK_B_IMPORT_LOG,
    il.DATA_IMPORTU,
    il.UZYTKOWNIK,
    il.NAZWA_PLIKU,
    il.LICZBA_WCZYTANYCH,
    il.LICZBA_DODANYCH,
    il.LICZBA_ZMODYFIKOWANYCH,
    il.LICZBA_DEZAKTYWOWANYCH,
    il.LICZBA_BEZ_ZMIAN,
    il.LICZBA_BLEDOW,
    il.STATUS_IMPORTU,
    il.KOMUNIKAT_BLEDU,
    -- Pole tekstowe do wyswietlenia skroconego podsumowania w APEX
    'Dodane: '        || il.LICZBA_DODANYCH         || ' | ' ||
    'Zmodyfikowane: ' || il.LICZBA_ZMODYFIKOWANYCH  || ' | ' ||
    'Dezaktywowane: ' || il.LICZBA_DEZAKTYWOWANYCH  || ' | ' ||
    'Bledy: '         || il.LICZBA_BLEDOW            AS PODSUMOWANIE
FROM
    B_IMPORT_LOG il
ORDER BY
    il.DATA_IMPORTU DESC;

   COMMENT ON COLUMN "B_AUDYT"."STATUS_AUDYTU" IS 'Status audytu: Otwarty=edycja mozliwa, Zamrozony=brak zmian listy kontroli, Zakonczony=brak jakichkolwiek zmian';
   COMMENT ON COLUMN "B_AUDYT"."SZEF_MISJI_LOGIN" IS 'Login LDAP (APP_USER) szefa misji – zapisywany przy tworzeniu rekordu, tylko on moze zamrozic/zakonczyc audyt';
   COMMENT ON COLUMN "B_AUDYT"."AUDYTORZY_LOGINY" IS 'Loginy LDAP audytorow uprawnionych do edycji, oddzielone przecinkiem (np. JAN.KOWALSKI,ANNA.NOWAK)';
   COMMENT ON COLUMN "B_AUDYT"."DATA_ZAMROZENIA" IS 'Data zamrozenia listy kontroli przez szefa misji';
   COMMENT ON COLUMN "B_AUDYT"."DATA_ZAKONCZENIA" IS 'Data zakonczenia audytu przez szefa misji (brak dalszych zmian)';
   COMMENT ON TABLE "B_AUDYT"  IS 'Tabela audytow. Cykl zycia statusu: Otwarty -> Zamrozony -> Zakonczony.';

   COMMENT ON COLUMN "B_AUDYT_KONTROLA"."DODAL_LOGIN" IS 'Login LDAP uzytkownika, ktory dodal kontrole do audytu';
   COMMENT ON TABLE "B_AUDYT_KONTROLA"  IS 'Lista kontroli przypisanych do audytu. INSERT/DELETE mozliwy tylko gdy STATUS_AUDYTU=Otwarty (wymuszane przez PKG_AUDYT).';

   COMMENT ON COLUMN "B_IMPORT_LOG"."UZYTKOWNIK" IS 'Login LDAP uzytkownika APEX (APP_USER), ktory uruchomil import';
   COMMENT ON COLUMN "B_IMPORT_LOG"."STATUS_IMPORTU" IS 'W_TOKU=import trwa, ZAKONCZONE=sukces, BLAD_KRYTYCZNY=nieobsluzony wyjatek';
   COMMENT ON TABLE "B_IMPORT_LOG"  IS 'Log kazdego uruchomienia importu kontroli z Excela. Jeden rekord = jeden import.';

   COMMENT ON COLUMN "B_KONTROLA"."DATA_DEZAKTYWACJI" IS 'Data ustawienia STATUS=Deactive (brak rekordu w pliku importu). NULL gdy aktywny.';
   COMMENT ON COLUMN "B_KONTROLA"."ID_FK_B_IMPORT_LOG" IS 'Ostatni import, ktory modyfikowal ten rekord (FK do B_IMPORT_LOG)';
   COMMENT ON TABLE "B_KONTROLA"  IS 'WITH kontrole AS (
SELECT
	a.REFERENCE AS REFERENCE_id,
	max(a.AS_OF_DATE) AS data_ostatniej_kontroli,
	min(a.AS_OF_DATE) AS data_pierwszej_kontroli,
	count(1) AS liczba_wykonanych_kontroli
FROM
	ZKW_GRP.SCOPE_DEFINITION_2024 a
GROUP BY
	a.REFERENCE)
SELECT
	DISTINCT aa.*,
b.STATUS,
b.CONTROL_LEVEL ,
b.DESCRIPTION____FR_ ,
b.DESCRIPTION____EN_ ,
b.SHORT_DESCRIPTION____FR_,
b.SHORT_DESCRIPTION____EN_,
b.DEFINITION____FR_,
b.DEFINITION____EN_,
b.OBJECTIVE____FR_,
b.OBJECTIVE____EN_,
b.DOMAIN_PROCESS,
b.RISKS,
b.CONTROL_GROUP
FROM
	kontrole aa
JOIN ZKW_GRP.SCOPE_DEFINITION_2024 b ON
	aa.REFERENCE_id = b.REFERENCE
	AND aa.data_ostatniej_kontroli = b.AS_OF_DATE';

   COMMENT ON COLUMN "B_KONTROLA_HIST"."ID_FK_B_KONTROLA" IS 'Klucz obcy do B_KONTROLA – nie zmienia sie przy aktualizacjach';
   COMMENT ON COLUMN "B_KONTROLA_HIST"."ID_FK_B_IMPORT_LOG" IS 'Import, ktory spowodowal zmiane';
   COMMENT ON COLUMN "B_KONTROLA_HIST"."DATA_ARCHIWIZACJI" IS 'Kiedy stara wersja zostala zarchiwizowana (= moment importu)';
   COMMENT ON TABLE "B_KONTROLA_HIST"  IS 'Historia zmian tabeli B_KONTROLA. Kazda aktualizacja importem zapisuje tu poprzednia wersje rekordu.';

   COMMENT ON COLUMN "B_KONTROLA_IMPORT"."ID_SESJI_IMPORTU" IS 'Laczy wiersze z konkretna sesja importu (B_IMPORT_LOG.ID_PK_B_IMPORT_LOG)';
   COMMENT ON COLUMN "B_KONTROLA_IMPORT"."STATUS_WIERSZA" IS 'NOWY=oczekuje na przetworzenie, OK=przetworzony, BLAD=blad walidacji';
   COMMENT ON TABLE "B_KONTROLA_IMPORT"  IS 'Tabela stagingowa do importu kontroli z pliku Excel przez APEX. Czyszczona po kazdym zakonczonym imporcie.';

   COMMENT ON TABLE "B_KONTROLA_TMP"  IS 'tabela tymczasowa z ID kontroli w audycie IT - tabela do skasowania w przyszłości';

   COMMENT ON TABLE "B_OCENA"  IS 'CREATE TABLE B_ODPOWIEDZ AS 	
SELECT
	DISTINCT 
	ID_FK_B_AUDYT,
	ID_FK_B_KONTROLA,
	B_SL_C_PYTANIE_DZIEDZINA_ID
FROM
	B_ANKIETA';

   COMMENT ON TABLE "B_SL_C_PYTANIE"  IS 'Słownik pytań do zakładki C. Ocena kontroli';

   COMMENT ON TABLE "B_V_AUDYT_KONTROLE"  IS 'Widok: kontrole przypisane do audytow z pelnymi danymi. Zrodlo danych dla stron APEX audytu.';

   COMMENT ON TABLE "B_V_IMPORT_STATYSTYKI"  IS 'Widok: historia importow kontroli z podsumowaniem statystyk. Zrodlo danych dla strony logow importu w APEX.';



































  CREATE UNIQUE INDEX "B_ANKIETA_CON" ON "B_ANKIETA" ("ID_PK_B_ANKIETA") 
  ;

  CREATE UNIQUE INDEX "B_AUDYT_PK" ON "B_AUDYT" ("ID_PK_B_AUDYT") 
  ;

   COMMENT ON COLUMN "B_AUDYT"."STATUS_AUDYTU" IS 'Status audytu: Otwarty=edycja mozliwa, Zamrozony=brak zmian listy kontroli, Zakonczony=brak jakichkolwiek zmian';
   COMMENT ON COLUMN "B_AUDYT"."SZEF_MISJI_LOGIN" IS 'Login LDAP (APP_USER) szefa misji – zapisywany przy tworzeniu rekordu, tylko on moze zamrozic/zakonczyc audyt';
   COMMENT ON COLUMN "B_AUDYT"."AUDYTORZY_LOGINY" IS 'Loginy LDAP audytorow uprawnionych do edycji, oddzielone przecinkiem (np. JAN.KOWALSKI,ANNA.NOWAK)';
   COMMENT ON COLUMN "B_AUDYT"."DATA_ZAMROZENIA" IS 'Data zamrozenia listy kontroli przez szefa misji';
   COMMENT ON COLUMN "B_AUDYT"."DATA_ZAKONCZENIA" IS 'Data zakonczenia audytu przez szefa misji (brak dalszych zmian)';
   COMMENT ON TABLE "B_AUDYT"  IS 'Tabela audytow. Cykl zycia statusu: Otwarty -> Zamrozony -> Zakonczony.';

  CREATE UNIQUE INDEX "B_AUDYT_KONTROLA_PK" ON "B_AUDYT_KONTROLA" ("ID_PK_B_AUDYT_KONTROLA") 
  ;
  CREATE UNIQUE INDEX "B_AUDYT_KONTROLA_UNQ" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT", "ID_FK_B_KONTROLA") 
  ;
  CREATE INDEX "B_AUDYT_KONTROLA_IDX1" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT") 
  ;
  CREATE INDEX "B_AUDYT_KONTROLA_IDX2" ON "B_AUDYT_KONTROLA" ("ID_FK_B_KONTROLA") 
  ;

   COMMENT ON COLUMN "B_AUDYT_KONTROLA"."DODAL_LOGIN" IS 'Login LDAP uzytkownika, ktory dodal kontrole do audytu';
   COMMENT ON TABLE "B_AUDYT_KONTROLA"  IS 'Lista kontroli przypisanych do audytu. INSERT/DELETE mozliwy tylko gdy STATUS_AUDYTU=Otwarty (wymuszane przez PKG_AUDYT).';

  CREATE UNIQUE INDEX "B_IMPORT_LOG_PK" ON "B_IMPORT_LOG" ("ID_PK_B_IMPORT_LOG") 
  ;

   COMMENT ON COLUMN "B_IMPORT_LOG"."UZYTKOWNIK" IS 'Login LDAP uzytkownika APEX (APP_USER), ktory uruchomil import';
   COMMENT ON COLUMN "B_IMPORT_LOG"."STATUS_IMPORTU" IS 'W_TOKU=import trwa, ZAKONCZONE=sukces, BLAD_KRYTYCZNY=nieobsluzony wyjatek';
   COMMENT ON TABLE "B_IMPORT_LOG"  IS 'Log kazdego uruchomienia importu kontroli z Excela. Jeden rekord = jeden import.';

  CREATE UNIQUE INDEX "SYS_C0052791" ON "B_KONTROLA" ("ID_PK_B_KONTROLA") 
  ;

   COMMENT ON COLUMN "B_KONTROLA"."DATA_DEZAKTYWACJI" IS 'Data ustawienia STATUS=Deactive (brak rekordu w pliku importu). NULL gdy aktywny.';
   COMMENT ON COLUMN "B_KONTROLA"."ID_FK_B_IMPORT_LOG" IS 'Ostatni import, ktory modyfikowal ten rekord (FK do B_IMPORT_LOG)';
   COMMENT ON TABLE "B_KONTROLA"  IS 'WITH kontrole AS (
SELECT
	a.REFERENCE AS REFERENCE_id,
	max(a.AS_OF_DATE) AS data_ostatniej_kontroli,
	min(a.AS_OF_DATE) AS data_pierwszej_kontroli,
	count(1) AS liczba_wykonanych_kontroli
FROM
	ZKW_GRP.SCOPE_DEFINITION_2024 a
GROUP BY
	a.REFERENCE)
SELECT
	DISTINCT aa.*,
b.STATUS,
b.CONTROL_LEVEL ,
b.DESCRIPTION____FR_ ,
b.DESCRIPTION____EN_ ,
b.SHORT_DESCRIPTION____FR_,
b.SHORT_DESCRIPTION____EN_,
b.DEFINITION____FR_,
b.DEFINITION____EN_,
b.OBJECTIVE____FR_,
b.OBJECTIVE____EN_,
b.DOMAIN_PROCESS,
b.RISKS,
b.CONTROL_GROUP
FROM
	kontrole aa
JOIN ZKW_GRP.SCOPE_DEFINITION_2024 b ON
	aa.REFERENCE_id = b.REFERENCE
	AND aa.data_ostatniej_kontroli = b.AS_OF_DATE';

  CREATE UNIQUE INDEX "B_KONTROLA_HIST_PK" ON "B_KONTROLA_HIST" ("ID_PK_B_KONTROLA_HIST") 
  ;
  CREATE INDEX "B_KONTROLA_HIST_IDX1" ON "B_KONTROLA_HIST" ("ID_FK_B_KONTROLA") 
  ;
  CREATE INDEX "B_KONTROLA_HIST_IDX2" ON "B_KONTROLA_HIST" ("ID_FK_B_IMPORT_LOG") 
  ;

   COMMENT ON COLUMN "B_KONTROLA_HIST"."ID_FK_B_KONTROLA" IS 'Klucz obcy do B_KONTROLA – nie zmienia sie przy aktualizacjach';
   COMMENT ON COLUMN "B_KONTROLA_HIST"."ID_FK_B_IMPORT_LOG" IS 'Import, ktory spowodowal zmiane';
   COMMENT ON COLUMN "B_KONTROLA_HIST"."DATA_ARCHIWIZACJI" IS 'Kiedy stara wersja zostala zarchiwizowana (= moment importu)';
   COMMENT ON TABLE "B_KONTROLA_HIST"  IS 'Historia zmian tabeli B_KONTROLA. Kazda aktualizacja importem zapisuje tu poprzednia wersje rekordu.';

  CREATE UNIQUE INDEX "B_KONTROLA_IMPORT_PK" ON "B_KONTROLA_IMPORT" ("ID") 
  ;
  CREATE INDEX "B_KONTROLA_IMPORT_IDX1" ON "B_KONTROLA_IMPORT" ("ID_SESJI_IMPORTU", "STATUS_WIERSZA") 
  ;

   COMMENT ON COLUMN "B_KONTROLA_IMPORT"."ID_SESJI_IMPORTU" IS 'Laczy wiersze z konkretna sesja importu (B_IMPORT_LOG.ID_PK_B_IMPORT_LOG)';
   COMMENT ON COLUMN "B_KONTROLA_IMPORT"."STATUS_WIERSZA" IS 'NOWY=oczekuje na przetworzenie, OK=przetworzony, BLAD=blad walidacji';
   COMMENT ON TABLE "B_KONTROLA_IMPORT"  IS 'Tabela stagingowa do importu kontroli z pliku Excel przez APEX. Czyszczona po kazdym zakonczonym imporcie.';

  CREATE UNIQUE INDEX "SYS_C0052793" ON "B_KONTROLA_TMP" ("ID") 
  ;

   COMMENT ON TABLE "B_KONTROLA_TMP"  IS 'tabela tymczasowa z ID kontroli w audycie IT - tabela do skasowania w przyszłości';

  CREATE UNIQUE INDEX "B_ODPOWIEDZ_PK" ON "B_OCENA" ("ID_PK_B_OCENA") 
  ;

   COMMENT ON TABLE "B_OCENA"  IS 'CREATE TABLE B_ODPOWIEDZ AS 	
SELECT
	DISTINCT 
	ID_FK_B_AUDYT,
	ID_FK_B_KONTROLA,
	B_SL_C_PYTANIE_DZIEDZINA_ID
FROM
	B_ANKIETA';

  CREATE UNIQUE INDEX "B_SL_C_PYTANIE_PK" ON "B_SL_C_PYTANIE" ("ID_PK_B_SL_C_PYTANIE") 
  ;
  CREATE UNIQUE INDEX "SYS_IL0000082378C00005$$" ON "B_SL_C_PYTANIE" (
  ;

   COMMENT ON TABLE "B_SL_C_PYTANIE"  IS 'Słownik pytań do zakładki C. Ocena kontroli';

  CREATE UNIQUE INDEX "B_SL_C_PYTANIE_DZIEDZINA_PK" ON "B_SL_C_PYTANIE_DZIEDZINA" ("ID_PK_B_C_PYTANIE_DZIEDZINA") 
  ;

   COMMENT ON TABLE "B_V_AUDYT_KONTROLE"  IS 'Widok: kontrole przypisane do audytow z pelnymi danymi. Zrodlo danych dla stron APEX audytu.';

   COMMENT ON TABLE "B_V_IMPORT_STATYSTYKI"  IS 'Widok: historia importow kontroli z podsumowaniem statystyk. Zrodlo danych dla strony logow importu w APEX.';














create or replace PACKAGE BODY PKG_AUDYT AS

    -- =========================================================================
    -- Procedura wewnetrzna: pobierz rekord audytu lub rzuc wyjatek
    -- =========================================================================
    PROCEDURE POBIERZ_AUDYT (
        p_id_audytu IN  NUMBER,
        v_audyt     OUT B_AUDYT%ROWTYPE
    ) IS
    BEGIN
        SELECT * INTO v_audyt
        FROM   B_AUDYT
        WHERE  ID_PK_B_AUDYT = p_id_audytu;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001,
                'Audyt o ID=' || p_id_audytu || ' nie istnieje.');
    END POBIERZ_AUDYT;


    -- =========================================================================
    -- FUNKCJA: SPRAWDZ_UPRAWNIENIA
    -- Zwraca role uzytkownika w kontekscie danego audytu.
    -- Porownanie case-insensitive (LDAP moze zwracac rozny case).
    -- =========================================================================
    FUNCTION SPRAWDZ_UPRAWNIENIA (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) RETURN VARCHAR2 IS
        v_audyt     B_AUDYT%ROWTYPE;
        v_login_uc  VARCHAR2(100);
    BEGIN
        POBIERZ_AUDYT(p_id_audytu, v_audyt);
        v_login_uc := UPPER(TRIM(p_uzytkownik));

        -- Sprawdz czy to szef misji
        IF UPPER(TRIM(v_audyt.SZEF_MISJI_LOGIN)) = v_login_uc THEN
            RETURN 'SZEF';
        END IF;

        -- Sprawdz czy login jest na liscie audytorow (separator: przecinek)
        -- Technika: otaczamy caly ciag i szukany login przecinkami
        IF v_audyt.AUDYTORZY_LOGINY IS NOT NULL THEN
            IF INSTR(',' || UPPER(v_audyt.AUDYTORZY_LOGINY) || ',',
                     ',' || v_login_uc || ',') > 0 THEN
                RETURN 'AUDYTOR';
            END IF;
        END IF;

        RETURN 'BRAK';
    END SPRAWDZ_UPRAWNIENIA;


    -- =========================================================================
    -- FUNKCJA: MOZE_EDYTOWAC
    -- Czy uzytkownik moze edytowac dane (ankiete, odpowiedzi) w audycie?
    -- Warunek: (SZEF lub AUDYTOR) ORAZ audyt nie jest Zakonczony.
    -- =========================================================================
    FUNCTION MOZE_EDYTOWAC (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) RETURN BOOLEAN IS
        v_audyt         B_AUDYT%ROWTYPE;
        v_uprawnienia   VARCHAR2(20);
    BEGIN
        POBIERZ_AUDYT(p_id_audytu, v_audyt);

        -- Zakonczony audyt = brak edycji dla nikogo
        IF v_audyt.STATUS_AUDYTU = C_STATUS_ZAKONCZONY THEN
            RETURN FALSE;
        END IF;

        v_uprawnienia := SPRAWDZ_UPRAWNIENIA(p_id_audytu, p_uzytkownik);
        RETURN v_uprawnienia IN ('SZEF', 'AUDYTOR');
    END MOZE_EDYTOWAC;


    -- =========================================================================
    -- PROCEDURA: UTWORZ_AUDYT
    -- =========================================================================
    PROCEDURE UTWORZ_AUDYT (
        p_numer_audytu  IN  VARCHAR2,
        p_uzytkownik    IN  VARCHAR2,
        p_id_audytu     OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO B_AUDYT (
            B_AUDYT_NUMER_AUDYTU,
            STATUS_AUDYTU,
            SZEF_MISJI_LOGIN,
            DATA_UTWORZENIA
        ) VALUES (
            p_numer_audytu,
            C_STATUS_OTWARTY,
            p_uzytkownik,
            SYSDATE
        ) RETURNING ID_PK_B_AUDYT INTO p_id_audytu;

        COMMIT;
    END UTWORZ_AUDYT;


    -- =========================================================================
    -- PROCEDURA: DODAJ_KONTROLE
    -- =========================================================================
    PROCEDURE DODAJ_KONTROLE (
        p_id_audytu     IN NUMBER,
        p_id_kontrola   IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) IS
        v_audyt         B_AUDYT%ROWTYPE;
        v_uprawnienia   VARCHAR2(20);
    BEGIN
        POBIERZ_AUDYT(p_id_audytu, v_audyt);

        -- Dodawanie mozliwe tylko gdy audyt jest Otwarty
        IF v_audyt.STATUS_AUDYTU != C_STATUS_OTWARTY THEN
            RAISE_APPLICATION_ERROR(-20010,
                'Nie mozna dodac kontroli. Audyt jest w statusie: ' ||
                v_audyt.STATUS_AUDYTU ||
                '. Modyfikacja listy kontroli mozliwa tylko dla statusu Otwarty.');
        END IF;

        -- Sprawdz uprawnienia uzytkownika
        v_uprawnienia := SPRAWDZ_UPRAWNIENIA(p_id_audytu, p_uzytkownik);
        IF v_uprawnienia = 'BRAK' THEN
            RAISE_APPLICATION_ERROR(-20011,
                'Brak uprawnien do modyfikacji listy kontroli audytu ID=' ||
                p_id_audytu || '. Wymagana rola: Szef misji lub Audytor.');
        END IF;

        INSERT INTO B_AUDYT_KONTROLA (
            ID_FK_B_AUDYT, ID_FK_B_KONTROLA, DODAL_LOGIN
        ) VALUES (
            p_id_audytu, p_id_kontrola, p_uzytkownik
        );

        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20012,
                'Kontrola ID=' || p_id_kontrola ||
                ' jest juz przypisana do tego audytu.');
    END DODAJ_KONTROLE;


    -- =========================================================================
    -- PROCEDURA: USUN_KONTROLE
    -- =========================================================================
    PROCEDURE USUN_KONTROLE (
        p_id_audytu     IN NUMBER,
        p_id_kontrola   IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) IS
        v_audyt         B_AUDYT%ROWTYPE;
        v_uprawnienia   VARCHAR2(20);
    BEGIN
        POBIERZ_AUDYT(p_id_audytu, v_audyt);

        -- Usuwanie mozliwe tylko gdy audyt jest Otwarty
        IF v_audyt.STATUS_AUDYTU != C_STATUS_OTWARTY THEN
            RAISE_APPLICATION_ERROR(-20020,
                'Nie mozna usunac kontroli. Audyt jest w statusie: ' ||
                v_audyt.STATUS_AUDYTU ||
                '. Modyfikacja listy kontroli mozliwa tylko dla statusu Otwarty.');
        END IF;

        -- Sprawdz uprawnienia uzytkownika
        v_uprawnienia := SPRAWDZ_UPRAWNIENIA(p_id_audytu, p_uzytkownik);
        IF v_uprawnienia = 'BRAK' THEN
            RAISE_APPLICATION_ERROR(-20021,
                'Brak uprawnien do modyfikacji listy kontroli audytu ID=' ||
                p_id_audytu || '.');
        END IF;

        DELETE FROM B_AUDYT_KONTROLA
        WHERE  ID_FK_B_AUDYT    = p_id_audytu
          AND  ID_FK_B_KONTROLA = p_id_kontrola;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20022,
                'Kontrola ID=' || p_id_kontrola ||
                ' nie jest przypisana do tego audytu.');
        END IF;

        COMMIT;
    END USUN_KONTROLE;


    -- =========================================================================
    -- PROCEDURA: ZAMROZ_AUDYT
    -- Mozliwe przejscie: Otwarty → Zamrozony (tylko szef misji)
    -- =========================================================================
    PROCEDURE ZAMROZ_AUDYT (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) IS
        v_audyt     B_AUDYT%ROWTYPE;
    BEGIN
        POBIERZ_AUDYT(p_id_audytu, v_audyt);

        -- Tylko szef misji moze zamrozic
        IF UPPER(TRIM(v_audyt.SZEF_MISJI_LOGIN)) != UPPER(TRIM(p_uzytkownik)) THEN
            RAISE_APPLICATION_ERROR(-20030,
                'Tylko szef misji moze zamrozic audyt. ' ||
                'Szef misji tego audytu: ' || v_audyt.SZEF_MISJI_LOGIN || '.');
        END IF;

        -- Mozna zamrozic tylko audyt Otwarty
        IF v_audyt.STATUS_AUDYTU != C_STATUS_OTWARTY THEN
            RAISE_APPLICATION_ERROR(-20031,
                'Audyt nie jest w statusie Otwarty. ' ||
                'Aktualny status: ' || v_audyt.STATUS_AUDYTU || '.');
        END IF;

        UPDATE B_AUDYT
        SET    STATUS_AUDYTU   = C_STATUS_ZAMROZONY,
               DATA_ZAMROZENIA = SYSDATE,
               ZAMROZIL_LOGIN  = p_uzytkownik
        WHERE  ID_PK_B_AUDYT   = p_id_audytu;

        COMMIT;
    END ZAMROZ_AUDYT;


    -- =========================================================================
    -- PROCEDURA: ZAKONCZ_AUDYT
    -- Mozliwe przejscie: Zamrozony → Zakonczony (tylko szef misji)
    -- =========================================================================
    PROCEDURE ZAKONCZ_AUDYT (
        p_id_audytu     IN NUMBER,
        p_uzytkownik    IN VARCHAR2
    ) IS
        v_audyt     B_AUDYT%ROWTYPE;
    BEGIN
        POBIERZ_AUDYT(p_id_audytu, v_audyt);

        -- Tylko szef misji moze zakonczyc
        IF UPPER(TRIM(v_audyt.SZEF_MISJI_LOGIN)) != UPPER(TRIM(p_uzytkownik)) THEN
            RAISE_APPLICATION_ERROR(-20040,
                'Tylko szef misji moze zakonczyc audyt. ' ||
                'Szef misji tego audytu: ' || v_audyt.SZEF_MISJI_LOGIN || '.');
        END IF;

        -- Musi byc najpierw Zamrozony (wymagana kolejnosc statusow)
        IF v_audyt.STATUS_AUDYTU != C_STATUS_ZAMROZONY THEN
            RAISE_APPLICATION_ERROR(-20041,
                'Audyt musi byc najpierw zamrozony zanim zostanie zakonczony. ' ||
                'Aktualny status: ' || v_audyt.STATUS_AUDYTU || '.');
        END IF;

        UPDATE B_AUDYT
        SET    STATUS_AUDYTU    = C_STATUS_ZAKONCZONY,
               DATA_ZAKONCZENIA = SYSDATE,
               ZAKONCZYL_LOGIN  = p_uzytkownik
        WHERE  ID_PK_B_AUDYT    = p_id_audytu;

        COMMIT;
    END ZAKONCZ_AUDYT;

END PKG_AUDYT;
/
create or replace PACKAGE BODY PKG_IMPORT_KONTROLI AS
    -- =========================================================================
    -- FUNKCJA: CZY_ROZNE
    -- Porownuje dwie wartosci VARCHAR2 z obsluga NULL.
    -- NULL vs NULL = brak zmiany; NULL vs wartosc = zmiana.
    -- =========================================================================
    FUNCTION CZY_ROZNE (
        p_stara IN VARCHAR2,
        p_nowa  IN VARCHAR2
    ) RETURN BOOLEAN IS
    BEGIN
        IF p_stara IS NULL AND p_nowa IS NULL THEN
            RETURN FALSE;
        END IF;
        IF p_stara IS NULL OR p_nowa IS NULL THEN
            RETURN TRUE;
        END IF;
        RETURN p_stara <> p_nowa;
    END CZY_ROZNE;
    -- =========================================================================
    -- PROCEDURA: WALIDUJ_STAGING
    -- Sprawdza poprawnosc danych w tabeli stagingowej.
    -- Oznacza bledne wiersze – nie sa przetwarzane przez WYKONAJ_IMPORT.
    -- =========================================================================
    PROCEDURE WALIDUJ_STAGING (
        p_id_sesji_importu  IN NUMBER,
        p_id_log            IN NUMBER
    ) IS
        v_liczba_bledow NUMBER := 0;
    BEGIN
        -- Walidacja 1: REFERENCE_ID nie moze byc pusty
        UPDATE B_KONTROLA_IMPORT
        SET    STATUS_WIERSZA  = 'BLAD',
               BLAD_WALIDACJI  = 'Brak wartosci REFERENCE_ID – pole wymagane'
        WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
          AND  STATUS_WIERSZA   = 'NOWY'
          AND  REFERENCE_ID     IS NULL;
        -- Walidacja 2: duplikaty REFERENCE_ID w obrebie jednego pliku
        UPDATE B_KONTROLA_IMPORT
        SET    STATUS_WIERSZA  = 'BLAD',
               BLAD_WALIDACJI  = 'Duplikat REFERENCE_ID w wczytywanym pliku'
        WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
          AND  STATUS_WIERSZA   = 'NOWY'
          AND  REFERENCE_ID IN (
                SELECT REFERENCE_ID
                FROM   B_KONTROLA_IMPORT
                WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
                GROUP BY REFERENCE_ID
                HAVING COUNT(*) > 1
               );
        -- Zlicz bledy i zapisz w logu
        SELECT COUNT(*)
        INTO   v_liczba_bledow
        FROM   B_KONTROLA_IMPORT
        WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
          AND  STATUS_WIERSZA   = 'BLAD';
        UPDATE B_IMPORT_LOG
        SET    LICZBA_BLEDOW = v_liczba_bledow
        WHERE  ID_PK_B_IMPORT_LOG = p_id_log;
        -- Wiersze bez bledu oznacz jako gotowe do importu
        UPDATE B_KONTROLA_IMPORT
        SET    STATUS_WIERSZA = 'OK'
        WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
          AND  STATUS_WIERSZA   = 'NOWY';
        COMMIT;
    END WALIDUJ_STAGING;
    -- =========================================================================
    -- PROCEDURA: WYKONAJ_IMPORT
    -- Logika:
    --   1. Utworz rekord logu (status W_TOKU)
    --   2. Waliduj staging
    --   3. Dla kazdego REFERENCE_ID z stagingu:
    --        a) Brak w B_KONTROLA                       → INSERT nowego rekordu
    --        b) Istnieje + wykryto zmiany               → archiwizuj + UPDATE
    --        c) Istnieje + brak zmian                   → tylko statystyki
    --   4. Rekordy w B_KONTROLA nieobecne w pliku       → STATUS='Deactive'
    --   5. Zaktualizuj statystyki logu, wyczysc staging
    -- =========================================================================
    PROCEDURE WYKONAJ_IMPORT (
        p_id_sesji_importu  IN  NUMBER,
        p_nazwa_pliku       IN  VARCHAR2,
        p_uzytkownik        IN  VARCHAR2,
        p_id_log            OUT NUMBER
    ) IS
        v_dodane            NUMBER := 0;
        v_zmodyfikowane     NUMBER := 0;
        v_dezaktywowane     NUMBER := 0;
        v_bez_zmian         NUMBER := 0;
        v_wczytane          NUMBER := 0;
        v_kontrola          B_KONTROLA%ROWTYPE;
        v_zmiana_wykryta    BOOLEAN;
        -- Zmienna pomocnicza: SQLERRM nie moze byc uzywany bezposrednio w SQL
        v_blad_msg          VARCHAR2(4000);
    BEGIN
        -- ----------------------------------------------------------------
        -- Krok 1: Utworz rekord logu importu
        -- ----------------------------------------------------------------
        INSERT INTO B_IMPORT_LOG (
            UZYTKOWNIK, NAZWA_PLIKU, STATUS_IMPORTU
        ) VALUES (
            p_uzytkownik, p_nazwa_pliku, 'W_TOKU'
        ) RETURNING ID_PK_B_IMPORT_LOG INTO p_id_log;
        -- Commit tutaj: log bedzie widoczny nawet jesli import pozniej sie wywali
        COMMIT;
        -- ----------------------------------------------------------------
        -- Krok 2: Walidacja danych stagingowych
        -- ----------------------------------------------------------------
        WALIDUJ_STAGING(p_id_sesji_importu, p_id_log);
        -- Policz wiersze poprawne (bez bledow walidacji)
        SELECT COUNT(*)
        INTO   v_wczytane
        FROM   B_KONTROLA_IMPORT
        WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
          AND  STATUS_WIERSZA   = 'OK';
        -- ----------------------------------------------------------------
        -- Krok 3: Przetworzenie kazdego poprawnego wiersza stagingu
        -- ----------------------------------------------------------------
        FOR r IN (
            SELECT *
            FROM   B_KONTROLA_IMPORT
            WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
              AND  STATUS_WIERSZA   = 'OK'
        ) LOOP
            BEGIN
                -- Sprawdz czy REFERENCE_ID juz istnieje w B_KONTROLA
                BEGIN
                    SELECT *
                    INTO   v_kontrola
                    FROM   B_KONTROLA
                    WHERE  REFERENCE_ID = r.REFERENCE_ID;
                    -- -----------------------------------------------
                    -- Rekord ISTNIEJE – porownaj pola wersjonowane
                    -- -----------------------------------------------
                    v_zmiana_wykryta :=
                        CZY_ROZNE(v_kontrola.STATUS,                r.STATUS)               OR
                        CZY_ROZNE(v_kontrola.CONTROL_LEVEL,         r.CONTROL_LEVEL)         OR
                        CZY_ROZNE(v_kontrola.DESCRIPTION_FR_,       r.DESCRIPTION_FR_)       OR
                        CZY_ROZNE(v_kontrola.DESCRIPTION_EN_,       r.DESCRIPTION_EN_)       OR
                        CZY_ROZNE(v_kontrola.SHORT_DESCRIPTION_FR_, r.SHORT_DESCRIPTION_FR_) OR
                        CZY_ROZNE(v_kontrola.SHORT_DESCRIPTION_EN_, r.SHORT_DESCRIPTION_EN_) OR
                        CZY_ROZNE(v_kontrola.DEFINITION_FR_,        r.DEFINITION_FR_)        OR
                        CZY_ROZNE(v_kontrola.DEFINITION_EN_,        r.DEFINITION_EN_)        OR
                        CZY_ROZNE(v_kontrola.OBJECTIVE_FR_,         r.OBJECTIVE_FR_)         OR
                        CZY_ROZNE(v_kontrola.OBJECTIVE_EN_,         r.OBJECTIVE_EN_)         OR
                        CZY_ROZNE(v_kontrola.DOMAIN_PROCESS,        r.DOMAIN_PROCESS)        OR
                        CZY_ROZNE(v_kontrola.RISKS,                 r.RISKS)                 OR
                        CZY_ROZNE(v_kontrola.CONTROL_GROUP,         r.CONTROL_GROUP);
                    IF v_zmiana_wykryta THEN
                        -- Archiwizuj poprzednia wersje do tabeli historycznej
                        INSERT INTO B_KONTROLA_HIST (
                            ID_FK_B_KONTROLA,       ID_FK_B_IMPORT_LOG,
                            UZYTKOWNIK_ZMIANY,      REFERENCE_ID,
                            STATUS,                 CONTROL_LEVEL,
                            DESCRIPTION_FR_,        DESCRIPTION_EN_,
                            SHORT_DESCRIPTION_FR_,  SHORT_DESCRIPTION_EN_,
                            DEFINITION_FR_,         DEFINITION_EN_,
                            OBJECTIVE_FR_,          OBJECTIVE_EN_,
                            DOMAIN_PROCESS,         RISKS,
                            CONTROL_GROUP
                        ) VALUES (
                            v_kontrola.ID_PK_B_KONTROLA, p_id_log,
                            p_uzytkownik,                v_kontrola.REFERENCE_ID,
                            v_kontrola.STATUS,           v_kontrola.CONTROL_LEVEL,
                            v_kontrola.DESCRIPTION_FR_,  v_kontrola.DESCRIPTION_EN_,
                            v_kontrola.SHORT_DESCRIPTION_FR_, v_kontrola.SHORT_DESCRIPTION_EN_,
                            v_kontrola.DEFINITION_FR_,   v_kontrola.DEFINITION_EN_,
                            v_kontrola.OBJECTIVE_FR_,    v_kontrola.OBJECTIVE_EN_,
                            v_kontrola.DOMAIN_PROCESS,   v_kontrola.RISKS,
                            v_kontrola.CONTROL_GROUP
                        );
                        -- Zaktualizuj rekord glowny
                        -- WAZNE: ID_PK_B_KONTROLA nigdy sie nie zmienia
                        UPDATE B_KONTROLA
                        SET
                            STATUS                  = r.STATUS,
                            CONTROL_LEVEL           = r.CONTROL_LEVEL,
                            DESCRIPTION_FR_         = r.DESCRIPTION_FR_,
                            DESCRIPTION_EN_         = r.DESCRIPTION_EN_,
                            SHORT_DESCRIPTION_FR_   = r.SHORT_DESCRIPTION_FR_,
                            SHORT_DESCRIPTION_EN_   = r.SHORT_DESCRIPTION_EN_,
                            DEFINITION_FR_          = r.DEFINITION_FR_,
                            DEFINITION_EN_          = r.DEFINITION_EN_,
                            OBJECTIVE_FR_           = r.OBJECTIVE_FR_,
                            OBJECTIVE_EN_           = r.OBJECTIVE_EN_,
                            DOMAIN_PROCESS          = r.DOMAIN_PROCESS,
                            RISKS                   = r.RISKS,
                            CONTROL_GROUP           = r.CONTROL_GROUP,
                            DATA_DEZAKTYWACJI       = NULL,  -- przywroc jesli wczesniej dezaktywowano
                            ID_FK_B_IMPORT_LOG      = p_id_log
                        WHERE ID_PK_B_KONTROLA = v_kontrola.ID_PK_B_KONTROLA;
                        v_zmodyfikowane := v_zmodyfikowane + 1;
                    ELSE
                        -- Brak zmian – tylko zaktualizuj referencje do logu
                        UPDATE B_KONTROLA
                        SET    ID_FK_B_IMPORT_LOG = p_id_log,
                               DATA_DEZAKTYWACJI  = NULL   -- przywroc jesli wczesniej dezaktywowano
                        WHERE  ID_PK_B_KONTROLA   = v_kontrola.ID_PK_B_KONTROLA;
                        v_bez_zmian := v_bez_zmian + 1;
                    END IF;
                EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                        -- -----------------------------------------------
                        -- Rekord NIE ISTNIEJE – wstaw nowy
                        -- -----------------------------------------------
                        INSERT INTO B_KONTROLA (
                            REFERENCE_ID,           STATUS,
                            CONTROL_LEVEL,          DESCRIPTION_FR_,
                            DESCRIPTION_EN_,        SHORT_DESCRIPTION_FR_,
                            SHORT_DESCRIPTION_EN_,  DEFINITION_FR_,
                            DEFINITION_EN_,         OBJECTIVE_FR_,
                            OBJECTIVE_EN_,          DOMAIN_PROCESS,
                            RISKS,                  CONTROL_GROUP,
                            ID_FK_B_IMPORT_LOG
                        ) VALUES (
                            r.REFERENCE_ID,         r.STATUS,
                            r.CONTROL_LEVEL,        r.DESCRIPTION_FR_,
                            r.DESCRIPTION_EN_,      r.SHORT_DESCRIPTION_FR_,
                            r.SHORT_DESCRIPTION_EN_,r.DEFINITION_FR_,
                            r.DEFINITION_EN_,       r.OBJECTIVE_FR_,
                            r.OBJECTIVE_EN_,        r.DOMAIN_PROCESS,
                            r.RISKS,                r.CONTROL_GROUP,
                            p_id_log
                        );
                        v_dodane := v_dodane + 1;
                END;
            EXCEPTION
                WHEN OTHERS THEN
                    -- Blad nieobsluzony na poziomie wiersza – oznacz wiersz
                    -- SQLERRM nie moze byc uzywany bezposrednio w SQL, przypisujemy do zmiennej
                    v_blad_msg := SQLERRM;
                    UPDATE B_KONTROLA_IMPORT
                    SET    STATUS_WIERSZA = 'BLAD',
                           BLAD_WALIDACJI = 'Blad przetwarzania: ' || v_blad_msg
                    WHERE  ID = r.ID;
                    UPDATE B_IMPORT_LOG
                    SET    LICZBA_BLEDOW = LICZBA_BLEDOW + 1
                    WHERE  ID_PK_B_IMPORT_LOG = p_id_log;
            END;
        END LOOP;
        -- ----------------------------------------------------------------
        -- Krok 4: Dezaktywacja rekordow nieobecnych w pliku
        -- Rekord istnieje w B_KONTROLA ale brakuje go w stagingu tej sesji
        -- ----------------------------------------------------------------
        UPDATE B_KONTROLA k
        SET    k.STATUS             = 'Deactive',
               k.DATA_DEZAKTYWACJI  = SYSDATE,
               k.ID_FK_B_IMPORT_LOG = p_id_log
        WHERE  k.STATUS             != 'Deactive'
          AND  k.REFERENCE_ID NOT IN (
                   SELECT REFERENCE_ID
                   FROM   B_KONTROLA_IMPORT
                   WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu
                     AND  STATUS_WIERSZA   = 'OK'
               );
        v_dezaktywowane := SQL%ROWCOUNT;
        -- ----------------------------------------------------------------
        -- Krok 5: Zaktualizuj statystyki logu
        -- ----------------------------------------------------------------
        UPDATE B_IMPORT_LOG
        SET
            LICZBA_WCZYTANYCH       = v_wczytane,
            LICZBA_DODANYCH         = v_dodane,
            LICZBA_ZMODYFIKOWANYCH  = v_zmodyfikowane,
            LICZBA_DEZAKTYWOWANYCH  = v_dezaktywowane,
            LICZBA_BEZ_ZMIAN        = v_bez_zmian,
            STATUS_IMPORTU          = 'ZAKONCZONE'
        WHERE ID_PK_B_IMPORT_LOG = p_id_log;
        -- ----------------------------------------------------------------
        -- Krok 6: Wyczysc tabele stagingowa z tej sesji
        -- ----------------------------------------------------------------
        DELETE FROM B_KONTROLA_IMPORT
        WHERE  ID_SESJI_IMPORTU = p_id_sesji_importu;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            -- Blad krytyczny calego procesu – cofnij zmiany w B_KONTROLA
            ROLLBACK;
            -- Zapisz blad w logu (osobny COMMIT bo ROLLBACK cofnalby ten INSERT)
            -- SQLERRM nie moze byc uzywany bezposrednio w SQL, przypisujemy do zmiennej
            v_blad_msg := SQLERRM;
            UPDATE B_IMPORT_LOG
            SET    STATUS_IMPORTU    = 'BLAD_KRYTYCZNY',
                   KOMUNIKAT_BLEDU   = 'Blad krytyczny: ' || v_blad_msg
            WHERE  ID_PK_B_IMPORT_LOG = p_id_log;
            COMMIT;
            -- Ponow wyjatek do APEX (wyswietli komunikat bledu uzytkownikowi)
            RAISE;
    END WYKONAJ_IMPORT;
END PKG_IMPORT_KONTROLI;
/

















































