"""Współdzielone fixtures — przykładowe struktury YAML eksportu APEX."""
import pytest

from apex_export_to_md.models import (
    ApexApp, DDLColumn, DDLConstraint, DDLIndex, DDLPackage, DDLProcedure,
    DDLSchema, DDLSequence, DDLTable, DDLTrigger, DDLView,
)


@pytest.fixture
def rich_ddl_app() -> ApexApp:
    """Aplikacja z pełnym przekrojem obiektów DDL do testów rendererów."""
    parent = DDLTable(
        name="PARENT",
        columns=[DDLColumn(name="ID", data_type="NUMBER", nullable=False, primary_key=True)],
        constraints=[DDLConstraint(name="PARENT_PK", type="PRIMARY KEY", columns=["ID"])],
    )
    child = DDLTable(
        name="CHILD",
        columns=[
            DDLColumn(name="ID", data_type="NUMBER", nullable=False, primary_key=True,
                      identity=True, identity_def="GENERATED BY DEFAULT AS IDENTITY"),
            DDLColumn(name="PARENT_ID", data_type="NUMBER", nullable=False),
            DDLColumn(name="CODE", data_type="VARCHAR2(20)", default="'NEW'"),
        ],
        constraints=[
            DDLConstraint(name="CHILD_PK", type="PRIMARY KEY", columns=["ID"]),
            DDLConstraint(name="CHILD_PARENT_FK", type="FOREIGN KEY", columns=["PARENT_ID"],
                          ref_table="PARENT", ref_column="ID"),
            DDLConstraint(name="CHILD_CODE_UK", type="UNIQUE", columns=["CODE"]),
            DDLConstraint(name="CHILD_CODE_CHK", type="CHECK", check_condition="CODE IS NOT NULL"),
        ],
        comment="Tabela podrzędna",
        column_comments={"CODE": "Kod biznesowy"},
    )
    schema = DDLSchema(
        tables=[parent, child],
        views=[DDLView(name="CHILD_V", sql="SELECT ID, CODE FROM CHILD", comment="Widok dzieci")],
        packages=[DDLPackage(name="CHILD_PKG", code="PROCEDURE SAVE_CHILD;\n")],
        procedures=[DDLProcedure(name="SYNC_CHILD", code="PROCEDURE SYNC_CHILD IS BEGIN NULL; END;")],
        sequences=[DDLSequence(name="CHILD_SEQ", start_with="10", increment_by="5")],
        indexes=[DDLIndex(name="CHILD_CODE_IDX", table_name="CHILD", columns=["CODE"], unique=True)],
        triggers=[DDLTrigger(name="CHILD_BI", table_name="CHILD", code="BEFORE INSERT ON CHILD")],
    )
    return ApexApp(name="TEST_DDL", id="42", ddl_schema=schema)


@pytest.fixture
def sample_page_yaml() -> dict:
    """Minimalna strona użytkownika (wzór: DAW_LISTA_AUDYTOW)."""
    return {
        "id": 4,
        "identification": {
            "name": "DAW_LISTA_AUDYTOW",
            "alias": "DAW-LISTA-AUDYTOW",
            "title": "DAW_LISTA_AUDYTOW",
        },
        "appearance": {"page-mode": "Normal"},
        "security": {
            "authentication": "Page Requires Authentication",
            "page-access-protection": "Arguments Must Have Checksum",
        },
        "css": {"inline": ".highlight { color: red; }"},
        "regions": [
            {
                "identification": {
                    "name": "ListaAudytow",
                    "title": "Lista audytów",
                    "type": "Interactive Grid",
                },
                "source": {
                    "location": "Local Database",
                    "type": "Table / View",
                    "table-name": "B_AUDYT",
                },
                "layout": {
                    "sequence": 20,
                    "parent-region": "No Parent",
                    "slot": "BODY",
                },
                "attributes": {
                    "edit": {
                        "enabled": True,
                        "allowed-operations": ["Add Row", "Update Row", "Delete Row"],
                    },
                },
                "columns": [
                    {
                        "identification": {"column-name": "ID_PK_B_AUDYT", "type": "Hidden"},
                        "source": {
                            "database-column": "ID_PK_B_AUDYT",
                            "data-type": "NUMBER",
                            "primary-key": True,
                        },
                    },
                    {
                        "identification": {"column-name": "B_AUDYT_NUMER_AUDYTU", "type": "Link"},
                        "heading": {"heading": "Numer Audytu"},
                        "source": {
                            "database-column": "B_AUDYT_NUMER_AUDYTU",
                            "data-type": "VARCHAR2",
                            "primary-key": False,
                        },
                        "link": {"target": {"page": "6 # DAW_WYBOR_KONTROLI"}},
                    },
                ],
            },
        ],
        "page-items": [
            {
                "identification": {"name": "P4_FILTR_STATUS", "type": "Select List"},
                "label": {"label": "Status"},
                "list-of-values": {"list-of-values": "STATUS_AUDYTU # 123"},
                "source": {"type": "Null"},
            },
        ],
        "buttons": [
            {
                "identification": {"button-name": "UTWORZ_AUDYT"},
                "label": {"label": "Nowy audyt"},
                "behavior": {"action": "Submit Page"},
                "appearance": {"hot": True},
            },
        ],
        "processes": [
            {
                "identification": {"name": "Zapisz_Dane", "type": "Execute Code"},
                "source": {
                    "language": "PL/SQL",
                    "pl/sql-code": "BEGIN PKG_AUDYT.ZAPISZ(:P4_ID); END;",
                },
                "execution": {"point": "After Submit"},
                "server-side-condition": {"when-button-pressed": "SAVE # 999"},
            },
        ],
        "dynamic-actions": [
            {
                "identification": {"name": "Zmiana_statusu"},
                "when": {
                    "event": "Change",
                    "selection-type": "Item",
                    "item": "P4_STATUS",
                },
                "execution": {"event-scope": "Dynamic"},
                "actions": [
                    {
                        "identification": {"action": "Execute PL/SQL Code"},
                        "settings": {"pl/sql-code": "BEGIN NULL; END;"},
                        "affected-elements": {
                            "selection-type": "jQuery Selector",
                            "jquery-selector": "#region1",
                        },
                        "execution": {"fire-on-initialization": False},
                    },
                ],
            },
        ],
        "branches": [
            {
                "identification": {"name": "Go To Page 6"},
                "behavior": {
                    "type": "Page or URL (Redirect)",
                    "target": {"page": "6 # DAW_WYBOR_KONTROLI", "url": None},
                },
                "execution": {"point": "After Processing"},
                "server-side-condition": {"type": "Request = Value", "value": "SAVE"},
            },
        ],
        "validations": [
            {
                "identification": {"name": "Sprawdz_Numer"},
                "validation": {
                    "type": "PL/SQL Function Body",
                    "pl/sql-function-body": "RETURN :P4_NUMER IS NOT NULL;",
                },
            },
        ],
    }


@pytest.fixture
def sample_admin_page_yaml() -> dict:
    """Strona administracyjna (powinna być odfiltrowana)."""
    return {
        "id": 10000,
        "identification": {
            "name": "Administration",
            "alias": "ADMIN",
            "title": "Administration",
            "page-group": "Administration # 52840988022029242",
        },
        "appearance": {"page-mode": "Normal"},
        "security": {
            "authorization-scheme": "Administration Rights # 52839508229029280",
            "authentication": "Page Requires Authentication",
        },
    }


@pytest.fixture
def sample_lovs_yaml() -> list[dict]:
    """Przykładowe LOV-y trzech typów."""
    return [
        {
            "identification": {"name": "B_AUDYT.NUMER"},
            "source": {"type": "Table / View", "table-name": "B_AUDYT"},
            "column-mapping": {"return": "ID_PK_B_AUDYT", "display": "B_AUDYT_NUMER_AUDYTU"},
        },
        {
            "identification": {"name": "KONTROLE_SQL"},
            "source": {
                "type": "SQL Query",
                "sql-query": "SELECT id, name FROM B_KONTROLA WHERE active = 1",
            },
            "column-mapping": {"return": "id", "display": "name"},
        },
        {
            "identification": {"name": "TAK_NIE"},
            "source": {"type": "Static Values"},
            "entries": [
                {"entry": {"sequence": 1, "display": "Tak", "return": "1"}},
                {"entry": {"sequence": 2, "display": "Nie", "return": "0"}},
            ],
        },
    ]


@pytest.fixture
def sample_app_yaml() -> dict:
    """Główny plik aplikacji (f338.yaml)."""
    return {
        "id": 160,
        "identification": {"name": "SKW_2_APEX", "alias": "START338"},
    }


@pytest.fixture
def sample_authorizations_yaml() -> list[dict]:
    """Schematy autoryzacji."""
    return [
        {
            "identification": {"name": "AD Role"},
            "authorization-scheme": {"type": "PL/SQL Function Returning Boolean"},
            "settings": {"pl/sql-function-body": "RETURN TRUE;"},
        },
        {
            "identification": {"name": "Administration Rights"},
            "authorization-scheme": {"type": "Is In Role or Group"},
            "settings": {"type": "Application Role", "name(s)": "Administrator"},
        },
    ]


@pytest.fixture
def sample_nav_lists_yaml() -> list[dict]:
    """Lista nawigacyjna z dwoma wpisami (wzór: Navigation Menu)."""
    return [
        {
            "identification": {"name": "Navigation Menu"},
            "entries": [
                {
                    "label": {"label": "DAW_LISTA_AUDYTOW"},
                    "link": {"target": {"page": 4}},
                },
                {
                    "label": {"label": "DAW_IMPORT_KONTROLI"},
                    "link": {"target": {"page": 5}},
                },
            ],
        }
    ]


@pytest.fixture
def sample_app_items_yaml() -> list[dict]:
    """Zmienne globalne aplikacji (Application Items)."""
    return [
        {
            "identification": {"name": "B_APP_ID_AUDYT", "scope": "Application"},
        },
        {
            "identification": {"name": "G_FIRSTNAME", "scope": "Global"},
        },
    ]


@pytest.fixture
def sample_build_options_yaml() -> list[dict]:
    """Opcje budowania (Build Options) — dwa statusy."""
    return [
        {
            "identification": {"name": "Commented Out"},
            "status": {"status": "Exclude"},
        },
        {
            "identification": {"name": "Feature: Access Control"},
            "status": {"status": "Include"},
        },
    ]


@pytest.fixture
def sample_breadcrumbs_yaml() -> list[dict]:
    """Breadcrumb z dwoma wpisami."""
    return [
        {
            "identification": {"name": "Breadcrumb"},
            "entries": [
                {
                    "identification": {"name": "DAW_LISTA_AUDYTOW", "page-number": 4},
                    "link": {"target": {"page": 4}},
                },
                {
                    "identification": {"name": "Home", "page-number": 1},
                    "link": {"target": {"page": 1}},
                },
            ],
        }
    ]


@pytest.fixture
def sample_acl_roles_yaml() -> list[dict]:
    """Role ACL z polem static-id."""
    return [
        {
            "identification": {"name": "Administrator"},
            "advanced": {"static-id": "ADMINISTRATOR"},
        },
        {
            "identification": {"name": "Contributor"},
            "advanced": {"static-id": "CONTRIBUTOR"},
        },
    ]
