# tests/test_ddl_parser.py
"""Testy parsera DDL — podział na bloki, ekstrakcja obiektów."""
import pytest
from apex_export_to_md.parser.ddl_parser import (
    split_into_blocks,
    parse_create_table,
)
from apex_export_to_md.models.db_models import DbSchema


class TestSplitIntoBlocks:
    def test_simple_statements(self):
        sql = "CREATE TABLE A (ID NUMBER);\nCREATE TABLE B (ID NUMBER);"
        blocks = split_into_blocks(sql)
        assert len(blocks) == 2
        assert "CREATE TABLE A" in blocks[0]
        assert "CREATE TABLE B" in blocks[1]

    def test_semicolon_inside_string_preserved(self):
        """Średnik wewnątrz stringa COMMENT ON nie dzieli bloku."""
        sql = """COMMENT ON TABLE "T1" IS 'SELECT a; FROM b; WHERE c;';"""
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1
        assert "SELECT a; FROM b; WHERE c;" in blocks[0]

    def test_plsql_block_separated_by_slash(self):
        sql = (
            "CREATE TABLE A (ID NUMBER);\n"
            "create or replace PACKAGE PKG AS\n"
            "  PROCEDURE P1;\n"
            "END PKG;\n"
            "/\n"
            "CREATE TABLE B (ID NUMBER);"
        )
        blocks = split_into_blocks(sql)
        assert len(blocks) == 3
        block_texts = "\n".join(blocks)
        assert "CREATE TABLE A" in block_texts
        assert "PACKAGE PKG" in block_texts
        assert "CREATE TABLE B" in block_texts

    def test_escaped_quotes_in_string(self):
        """Podwójny apostrof '' nie kończy stringa."""
        sql = """COMMENT ON TABLE "T" IS 'It''s a test; with semicolon';"""
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1
        assert "It''s a test; with semicolon" in blocks[0]

    def test_empty_blocks_filtered(self):
        sql = "  ;\n\n  ; CREATE TABLE A (ID NUMBER);"
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1


class TestParseCreateTable:
    def test_simple_table(self):
        sql = '''CREATE TABLE "B_AUDYT"
           ("ID_PK_B_AUDYT" NUMBER NOT NULL ENABLE,
            "STATUS_AUDYTU" VARCHAR2(20) DEFAULT 'Otwarty' NOT NULL ENABLE,
            CONSTRAINT "B_AUDYT_PK" PRIMARY KEY ("ID_PK_B_AUDYT")
           USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        assert table is not None
        assert table.name == "B_AUDYT"
        assert len(table.columns) == 2
        id_col = table.columns[0]
        assert id_col.name == "ID_PK_B_AUDYT"
        assert id_col.data_type == "NUMBER"
        assert id_col.nullable is False
        status_col = table.columns[1]
        assert status_col.data_type == "VARCHAR2(20)"
        assert status_col.default == "'Otwarty'"
        assert status_col.nullable is False
        pk = [c for c in table.constraints if c.constraint_type == "PK"]
        assert len(pk) == 1
        assert pk[0].columns == ["ID_PK_B_AUDYT"]

    def test_identity_column(self):
        sql = '''CREATE TABLE "T"
           ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
            MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1
            CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
            CONSTRAINT "T_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].identity is True
        assert table.columns[0].nullable is False

    def test_check_constraint_inline(self):
        sql = '''CREATE TABLE "B_AUDYT"
           ("STATUS" VARCHAR2(20) NOT NULL ENABLE,
            CONSTRAINT "CHK1" CHECK (STATUS IN ('A','B','C')) ENABLE
           )'''
        table = parse_create_table(sql)
        chk = [c for c in table.constraints if c.constraint_type == "CHK"]
        assert len(chk) == 1
        assert "STATUS IN" in chk[0].check_expression

    def test_unique_constraint_inline(self):
        sql = '''CREATE TABLE "T"
           ("A" NUMBER NOT NULL, "B" NUMBER NOT NULL,
            CONSTRAINT "T_UNQ" UNIQUE ("A", "B") USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        uq = [c for c in table.constraints if c.constraint_type == "UQ"]
        assert len(uq) == 1
        assert uq[0].columns == ["A", "B"]

    def test_clob_and_date_types(self):
        sql = '''CREATE TABLE "T"
           ("POMOC" CLOB,
            "DATA" DATE DEFAULT SYSDATE,
            "TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].data_type == "CLOB"
        assert table.columns[1].data_type == "DATE"
        assert table.columns[1].default == "SYSDATE"
        assert "TIMESTAMP" in table.columns[2].data_type
        assert table.columns[2].nullable is False

    def test_sequence_default(self):
        """DEFAULT "DAW"."SEQ"."NEXTVAL" — parsuj jako default."""
        sql = '''CREATE TABLE "T"
           ("ID" NUMBER DEFAULT "DAW"."SEQ"."NEXTVAL" NOT NULL ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].default is not None
        assert "NEXTVAL" in table.columns[0].default
