# tests/test_ddl_parser.py
"""Testy parsera DDL — podział na bloki, ekstrakcja obiektów."""
import pytest
from apex_export_to_md.parser.ddl_parser import (
    split_into_blocks,
    parse_create_table,
    parse_alter_table_fk,
    parse_create_index,
    parse_comment_on,
    parse_create_sequence,
    parse_create_view,
    parse_package,
    parse_ddl,
    parse_ddl_files,
)
from apex_export_to_md.models.db_models import DbSchema


class TestSplitIntoBlocks:
    def test_simple_statements(self):
        sql = "CREATE TABLE A (ID NUMBER);\nCREATE TABLE B (ID NUMBER);"
        blocks = split_into_blocks(sql)
        assert len(blocks) == 2
        assert "CREATE TABLE A" in blocks[0]
        assert "CREATE TABLE B" in blocks[1]

    def test_semicolon_inside_string_preserved(self):
        """Średnik wewnątrz stringa COMMENT ON nie dzieli bloku."""
        sql = """COMMENT ON TABLE "T1" IS 'SELECT a; FROM b; WHERE c;';"""
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1
        assert "SELECT a; FROM b; WHERE c;" in blocks[0]

    def test_plsql_block_separated_by_slash(self):
        sql = (
            "CREATE TABLE A (ID NUMBER);\n"
            "create or replace PACKAGE PKG AS\n"
            "  PROCEDURE P1;\n"
            "END PKG;\n"
            "/\n"
            "CREATE TABLE B (ID NUMBER);"
        )
        blocks = split_into_blocks(sql)
        assert len(blocks) == 3
        block_texts = "\n".join(blocks)
        assert "CREATE TABLE A" in block_texts
        assert "PACKAGE PKG" in block_texts
        assert "CREATE TABLE B" in block_texts

    def test_escaped_quotes_in_string(self):
        """Podwójny apostrof '' nie kończy stringa."""
        sql = """COMMENT ON TABLE "T" IS 'It''s a test; with semicolon';"""
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1
        assert "It''s a test; with semicolon" in blocks[0]

    def test_empty_blocks_filtered(self):
        sql = "  ;\n\n  ; CREATE TABLE A (ID NUMBER);"
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1


class TestParseCreateTable:
    def test_simple_table(self):
        sql = '''CREATE TABLE "B_AUDYT"
           ("ID_PK_B_AUDYT" NUMBER NOT NULL ENABLE,
            "STATUS_AUDYTU" VARCHAR2(20) DEFAULT 'Otwarty' NOT NULL ENABLE,
            CONSTRAINT "B_AUDYT_PK" PRIMARY KEY ("ID_PK_B_AUDYT")
           USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        assert table is not None
        assert table.name == "B_AUDYT"
        assert len(table.columns) == 2
        id_col = table.columns[0]
        assert id_col.name == "ID_PK_B_AUDYT"
        assert id_col.data_type == "NUMBER"
        assert id_col.nullable is False
        status_col = table.columns[1]
        assert status_col.data_type == "VARCHAR2(20)"
        assert status_col.default == "'Otwarty'"
        assert status_col.nullable is False
        pk = [c for c in table.constraints if c.constraint_type == "PK"]
        assert len(pk) == 1
        assert pk[0].columns == ["ID_PK_B_AUDYT"]

    def test_identity_column(self):
        sql = '''CREATE TABLE "T"
           ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
            MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1
            CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
            CONSTRAINT "T_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].identity is True
        assert table.columns[0].nullable is False

    def test_check_constraint_inline(self):
        sql = '''CREATE TABLE "B_AUDYT"
           ("STATUS" VARCHAR2(20) NOT NULL ENABLE,
            CONSTRAINT "CHK1" CHECK (STATUS IN ('A','B','C')) ENABLE
           )'''
        table = parse_create_table(sql)
        chk = [c for c in table.constraints if c.constraint_type == "CHK"]
        assert len(chk) == 1
        assert "STATUS IN" in chk[0].check_expression

    def test_unique_constraint_inline(self):
        sql = '''CREATE TABLE "T"
           ("A" NUMBER NOT NULL, "B" NUMBER NOT NULL,
            CONSTRAINT "T_UNQ" UNIQUE ("A", "B") USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        uq = [c for c in table.constraints if c.constraint_type == "UQ"]
        assert len(uq) == 1
        assert uq[0].columns == ["A", "B"]

    def test_clob_and_date_types(self):
        sql = '''CREATE TABLE "T"
           ("POMOC" CLOB,
            "DATA" DATE DEFAULT SYSDATE,
            "TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].data_type == "CLOB"
        assert table.columns[1].data_type == "DATE"
        assert table.columns[1].default == "SYSDATE"
        assert "TIMESTAMP" in table.columns[2].data_type
        assert table.columns[2].nullable is False

    def test_sequence_default(self):
        """DEFAULT "DAW"."SEQ"."NEXTVAL" — parsuj jako default."""
        sql = '''CREATE TABLE "T"
           ("ID" NUMBER DEFAULT "DAW"."SEQ"."NEXTVAL" NOT NULL ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].default is not None
        assert "NEXTVAL" in table.columns[0].default


class TestParseAlterTableFK:
    def test_foreign_key(self):
        sql = '''ALTER TABLE "B_ANKIETA" ADD CONSTRAINT "B_ANKIETA_B_AUDYT_FK"
                 FOREIGN KEY ("ID_FK_B_AUDYT")
                 REFERENCES "B_AUDYT" ("ID_PK_B_AUDYT") ENABLE'''
        result = parse_alter_table_fk(sql)
        assert result is not None
        table_name, constraint = result
        assert table_name == "B_ANKIETA"
        assert constraint.name == "B_ANKIETA_B_AUDYT_FK"
        assert constraint.constraint_type == "FK"
        assert constraint.columns == ["ID_FK_B_AUDYT"]
        assert constraint.ref_table == "B_AUDYT"
        assert constraint.ref_columns == ["ID_PK_B_AUDYT"]

    def test_unique_constraint_via_alter(self):
        """ALTER TABLE z UNIQUE — parsuje jako constraint UQ."""
        sql = '''ALTER TABLE "T" ADD CONSTRAINT "T_UQ" UNIQUE ("A", "B")'''
        result = parse_alter_table_fk(sql)
        assert result is not None
        _, c = result
        assert c.constraint_type == "UQ"


class TestParseCreateIndex:
    def test_unique_index(self):
        sql = 'CREATE UNIQUE INDEX "B_AUDYT_PK" ON "B_AUDYT" ("ID_PK_B_AUDYT")'
        idx = parse_create_index(sql)
        assert idx is not None
        assert idx.name == "B_AUDYT_PK"
        assert idx.table_name == "B_AUDYT"
        assert idx.columns == ["ID_PK_B_AUDYT"]
        assert idx.unique is True

    def test_regular_index(self):
        sql = 'CREATE INDEX "B_AK_IDX1" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT")'
        idx = parse_create_index(sql)
        assert idx.unique is False

    def test_composite_index(self):
        sql = 'CREATE INDEX "IDX" ON "T" ("A", "B")'
        idx = parse_create_index(sql)
        assert idx.columns == ["A", "B"]

    def test_malformed_index_returns_none(self):
        """Niekompletny CREATE INDEX — brak kolumn."""
        sql = 'CREATE UNIQUE INDEX "SYS_IL0000082378C00005$$" ON "B_SL_C_PYTANIE" ('
        idx = parse_create_index(sql)
        assert idx is None


class TestParseCommentOn:
    def test_table_comment(self):
        sql = """COMMENT ON TABLE "B_AUDYT" IS 'Tabela audytow.'"""
        result = parse_comment_on(sql)
        assert result is not None
        obj_type, obj_name, col_name, text = result
        assert obj_type == "TABLE"
        assert obj_name == "B_AUDYT"
        assert col_name is None
        assert text == "Tabela audytow."

    def test_column_comment(self):
        sql = """COMMENT ON COLUMN "B_AUDYT"."STATUS_AUDYTU" IS 'Status audytu: Otwarty=edycja'"""
        result = parse_comment_on(sql)
        assert result is not None
        obj_type, obj_name, col_name, text = result
        assert obj_type == "COLUMN"
        assert obj_name == "B_AUDYT"
        assert col_name == "STATUS_AUDYTU"
        assert text == "Status audytu: Otwarty=edycja"

    def test_multiline_comment(self):
        """Komentarz z wieloliniowym SQL wewnątrz."""
        sql = """COMMENT ON TABLE "B_KONTROLA" IS 'WITH k AS (\nSELECT a FROM b\n)'"""
        result = parse_comment_on(sql)
        assert result is not None
        _, _, _, text = result
        assert "WITH k AS" in text


class TestParseCreateSequence:
    def test_sequence(self):
        sql = '''CREATE SEQUENCE "DAW_SEQ_B_C_ANAKIETA_PK"
                 MINVALUE 0 MAXVALUE 9999999 INCREMENT BY 1
                 START WITH 1203 NOCACHE NOORDER NOCYCLE'''
        seq = parse_create_sequence(sql)
        assert seq is not None
        assert seq.name == "DAW_SEQ_B_C_ANAKIETA_PK"
        assert seq.start_with == "1203"
        assert seq.increment_by == "1"
        assert seq.min_value == "0"


class TestParseCreateView:
    def test_view_with_columns(self):
        sql = '''CREATE OR REPLACE FORCE EDITIONABLE VIEW "B_V_TEST"
                 ("COL_A", "COL_B") AS
                 SELECT a.COL_A, b.COL_B
                 FROM TABLE_A a JOIN TABLE_B b ON a.ID = b.ID'''
        view = parse_create_view(sql)
        assert view is not None
        assert view.name == "B_V_TEST"
        assert view.columns == ["COL_A", "COL_B"]
        assert "SELECT" in view.sql
        assert "JOIN TABLE_B" in view.sql

    def test_view_without_column_list(self):
        sql = '''CREATE OR REPLACE VIEW "V1" AS SELECT * FROM T1'''
        view = parse_create_view(sql)
        assert view is not None
        assert view.name == "V1"
        assert view.columns == []
        assert "SELECT * FROM T1" in view.sql


class TestParsePackage:
    def test_package_spec(self):
        sql = '''create or replace PACKAGE PKG_TEST AS
    C_STATUS CONSTANT VARCHAR2(20) := 'Active';
    -- Tworzenie rekordu
    PROCEDURE CREATE_REC (
        p_name  IN  VARCHAR2,
        p_id    OUT NUMBER
    );
    -- Sprawdza status
    FUNCTION CHECK_STATUS (
        p_id IN NUMBER
    ) RETURN VARCHAR2;
END PKG_TEST;'''
        pkg = parse_package(sql)
        assert pkg is not None
        assert pkg.name == "PKG_TEST"
        assert len(pkg.spec_subprograms) == 2
        proc = pkg.spec_subprograms[0]
        assert proc.name == "CREATE_REC"
        assert proc.subprogram_type == "PROCEDURE"
        assert proc.description == "Tworzenie rekordu"
        assert len(proc.parameters) == 2
        assert proc.parameters[0].direction == "IN"
        assert proc.parameters[1].direction == "OUT"
        func = pkg.spec_subprograms[1]
        assert func.name == "CHECK_STATUS"
        assert func.subprogram_type == "FUNCTION"
        assert func.return_type == "VARCHAR2"
        assert len(pkg.constants) == 1
        assert "C_STATUS" in pkg.constants[0]

    def test_package_body(self):
        sql = '''create or replace PACKAGE BODY PKG_TEST AS
    -- Procedura wewnetrzna
    PROCEDURE HELPER (p_x IN NUMBER) IS
    BEGIN
        NULL;
    END HELPER;
    PROCEDURE CREATE_REC (p_name IN VARCHAR2, p_id OUT NUMBER) IS
    BEGIN
        NULL;
    END CREATE_REC;
END PKG_TEST;'''
        pkg = parse_package(sql)
        assert pkg is not None
        assert pkg.name == "PKG_TEST"
        assert len(pkg.body_subprograms) == 2
        assert pkg.body_subprograms[0].name == "HELPER"
        assert pkg.body_source != ""

    def test_package_body_full_source_preserved(self):
        """Pełny kod body (z komentarzami) zachowany w body_source."""
        sql = '''create or replace PACKAGE BODY PKG AS
    -- Komentarz ważny
    PROCEDURE P IS
    BEGIN
        -- Jeszcze komentarz
        NULL;
    END P;
END PKG;'''
        pkg = parse_package(sql)
        assert "Komentarz ważny" in pkg.body_source
        assert "Jeszcze komentarz" in pkg.body_source


class TestParseDdl:
    def test_full_parse(self):
        sql = '''
        CREATE TABLE "T1" ("ID" NUMBER NOT NULL, CONSTRAINT "T1_PK" PRIMARY KEY ("ID") USING INDEX ENABLE);
        ALTER TABLE "T2" ADD CONSTRAINT "T2_FK" FOREIGN KEY ("FK_ID") REFERENCES "T1" ("ID") ENABLE;
        CREATE INDEX "T2_IDX" ON "T2" ("FK_ID");
        COMMENT ON TABLE "T1" IS 'Tabela glowna';
        COMMENT ON COLUMN "T1"."ID" IS 'Klucz glowny';
        CREATE SEQUENCE "SEQ1" MINVALUE 0 MAXVALUE 999 INCREMENT BY 1 START WITH 100;
        CREATE OR REPLACE VIEW "V1" ("A", "B") AS SELECT a, b FROM T1;
        create or replace PACKAGE PKG AS
            PROCEDURE P1;
        END PKG;
        /
        '''
        schema = parse_ddl(sql)
        assert len(schema.tables) == 1
        assert schema.tables[0].name == "T1"
        assert schema.tables[0].comment == "Tabela glowna"
        assert schema.tables[0].columns[0].comment == "Klucz glowny"
        assert len(schema.views) == 1
        assert len(schema.sequences) == 1
        assert len(schema.packages) == 1

    def test_deduplication_first_wins(self):
        """Zduplikowane COMMENT ON — pierwszy wygrywa."""
        sql = '''
        CREATE TABLE "T" ("ID" NUMBER);
        COMMENT ON TABLE "T" IS 'Pierwszy komentarz';
        COMMENT ON TABLE "T" IS 'Drugi komentarz';
        '''
        schema = parse_ddl(sql)
        assert schema.tables[0].comment == "Pierwszy komentarz"

    def test_index_deduplication(self):
        sql = '''
        CREATE TABLE "T" ("ID" NUMBER);
        CREATE INDEX "IDX" ON "T" ("ID");
        CREATE INDEX "IDX" ON "T" ("ID");
        '''
        schema = parse_ddl(sql)
        assert len(schema.tables[0].indexes) == 1

    def test_package_spec_and_body_merged(self):
        sql = '''
        create or replace PACKAGE PKG AS
            PROCEDURE PUB;
        END PKG;
        /
        create or replace PACKAGE BODY PKG AS
            PROCEDURE PRIV IS BEGIN NULL; END PRIV;
            PROCEDURE PUB IS BEGIN NULL; END PUB;
        END PKG;
        /
        '''
        schema = parse_ddl(sql)
        assert len(schema.packages) == 1
        pkg = schema.packages[0]
        assert pkg.name == "PKG"
        assert len(pkg.spec_subprograms) == 1
        assert len(pkg.body_subprograms) == 2
        priv = [s for s in pkg.body_subprograms if s.name == "PRIV"]
        assert priv[0].visibility == "private"

    def test_malformed_block_skipped(self):
        sql = '''
        CREATE TABLE "T" ("ID" NUMBER);
        CREATE UNIQUE INDEX "BAD" ON "T" (;
        '''
        schema = parse_ddl(sql)
        assert len(schema.tables) == 1
        assert len(schema.tables[0].indexes) == 0

    def test_comment_on_view(self):
        """COMMENT ON TABLE z nazwą widoku — trafia do widoku."""
        sql = '''
        CREATE OR REPLACE VIEW "V1" AS SELECT 1 FROM DUAL;
        COMMENT ON TABLE "V1" IS 'Widok testowy';
        '''
        schema = parse_ddl(sql)
        assert schema.views[0].comment == "Widok testowy"


class TestParseDdlFiles:
    def test_parse_single_file(self, tmp_path):
        f = tmp_path / "test.sql"
        f.write_text('CREATE TABLE "T" ("ID" NUMBER);', encoding="utf-8")
        schema = parse_ddl_files([f])
        assert len(schema.tables) == 1

    def test_parse_multiple_files(self, tmp_path):
        f1 = tmp_path / "tables.sql"
        f1.write_text('CREATE TABLE "T1" ("ID" NUMBER);', encoding="utf-8")
        f2 = tmp_path / "views.sql"
        f2.write_text('CREATE OR REPLACE VIEW "V1" AS SELECT 1 FROM DUAL;', encoding="utf-8")
        schema = parse_ddl_files([f1, f2])
        assert len(schema.tables) == 1
        assert len(schema.views) == 1
