# tests/test_ddl_parser.py
"""Testy parsera DDL — podział na bloki, ekstrakcja obiektów."""
import pytest
from apex_export_to_md.parser.ddl_parser import (
    split_into_blocks,
    parse_create_table,
    parse_alter_table_fk,
    parse_create_index,
    parse_comment_on,
    parse_create_sequence,
)
from apex_export_to_md.models.db_models import DbSchema


class TestSplitIntoBlocks:
    def test_simple_statements(self):
        sql = "CREATE TABLE A (ID NUMBER);\nCREATE TABLE B (ID NUMBER);"
        blocks = split_into_blocks(sql)
        assert len(blocks) == 2
        assert "CREATE TABLE A" in blocks[0]
        assert "CREATE TABLE B" in blocks[1]

    def test_semicolon_inside_string_preserved(self):
        """Średnik wewnątrz stringa COMMENT ON nie dzieli bloku."""
        sql = """COMMENT ON TABLE "T1" IS 'SELECT a; FROM b; WHERE c;';"""
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1
        assert "SELECT a; FROM b; WHERE c;" in blocks[0]

    def test_plsql_block_separated_by_slash(self):
        sql = (
            "CREATE TABLE A (ID NUMBER);\n"
            "create or replace PACKAGE PKG AS\n"
            "  PROCEDURE P1;\n"
            "END PKG;\n"
            "/\n"
            "CREATE TABLE B (ID NUMBER);"
        )
        blocks = split_into_blocks(sql)
        assert len(blocks) == 3
        block_texts = "\n".join(blocks)
        assert "CREATE TABLE A" in block_texts
        assert "PACKAGE PKG" in block_texts
        assert "CREATE TABLE B" in block_texts

    def test_escaped_quotes_in_string(self):
        """Podwójny apostrof '' nie kończy stringa."""
        sql = """COMMENT ON TABLE "T" IS 'It''s a test; with semicolon';"""
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1
        assert "It''s a test; with semicolon" in blocks[0]

    def test_empty_blocks_filtered(self):
        sql = "  ;\n\n  ; CREATE TABLE A (ID NUMBER);"
        blocks = split_into_blocks(sql)
        assert len(blocks) == 1


class TestParseCreateTable:
    def test_simple_table(self):
        sql = '''CREATE TABLE "B_AUDYT"
           ("ID_PK_B_AUDYT" NUMBER NOT NULL ENABLE,
            "STATUS_AUDYTU" VARCHAR2(20) DEFAULT 'Otwarty' NOT NULL ENABLE,
            CONSTRAINT "B_AUDYT_PK" PRIMARY KEY ("ID_PK_B_AUDYT")
           USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        assert table is not None
        assert table.name == "B_AUDYT"
        assert len(table.columns) == 2
        id_col = table.columns[0]
        assert id_col.name == "ID_PK_B_AUDYT"
        assert id_col.data_type == "NUMBER"
        assert id_col.nullable is False
        status_col = table.columns[1]
        assert status_col.data_type == "VARCHAR2(20)"
        assert status_col.default == "'Otwarty'"
        assert status_col.nullable is False
        pk = [c for c in table.constraints if c.constraint_type == "PK"]
        assert len(pk) == 1
        assert pk[0].columns == ["ID_PK_B_AUDYT"]

    def test_identity_column(self):
        sql = '''CREATE TABLE "T"
           ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
            MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1
            CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
            CONSTRAINT "T_PK" PRIMARY KEY ("ID") USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].identity is True
        assert table.columns[0].nullable is False

    def test_check_constraint_inline(self):
        sql = '''CREATE TABLE "B_AUDYT"
           ("STATUS" VARCHAR2(20) NOT NULL ENABLE,
            CONSTRAINT "CHK1" CHECK (STATUS IN ('A','B','C')) ENABLE
           )'''
        table = parse_create_table(sql)
        chk = [c for c in table.constraints if c.constraint_type == "CHK"]
        assert len(chk) == 1
        assert "STATUS IN" in chk[0].check_expression

    def test_unique_constraint_inline(self):
        sql = '''CREATE TABLE "T"
           ("A" NUMBER NOT NULL, "B" NUMBER NOT NULL,
            CONSTRAINT "T_UNQ" UNIQUE ("A", "B") USING INDEX ENABLE
           )'''
        table = parse_create_table(sql)
        uq = [c for c in table.constraints if c.constraint_type == "UQ"]
        assert len(uq) == 1
        assert uq[0].columns == ["A", "B"]

    def test_clob_and_date_types(self):
        sql = '''CREATE TABLE "T"
           ("POMOC" CLOB,
            "DATA" DATE DEFAULT SYSDATE,
            "TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].data_type == "CLOB"
        assert table.columns[1].data_type == "DATE"
        assert table.columns[1].default == "SYSDATE"
        assert "TIMESTAMP" in table.columns[2].data_type
        assert table.columns[2].nullable is False

    def test_sequence_default(self):
        """DEFAULT "DAW"."SEQ"."NEXTVAL" — parsuj jako default."""
        sql = '''CREATE TABLE "T"
           ("ID" NUMBER DEFAULT "DAW"."SEQ"."NEXTVAL" NOT NULL ENABLE
           )'''
        table = parse_create_table(sql)
        assert table.columns[0].default is not None
        assert "NEXTVAL" in table.columns[0].default


class TestParseAlterTableFK:
    def test_foreign_key(self):
        sql = '''ALTER TABLE "B_ANKIETA" ADD CONSTRAINT "B_ANKIETA_B_AUDYT_FK"
                 FOREIGN KEY ("ID_FK_B_AUDYT")
                 REFERENCES "B_AUDYT" ("ID_PK_B_AUDYT") ENABLE'''
        result = parse_alter_table_fk(sql)
        assert result is not None
        table_name, constraint = result
        assert table_name == "B_ANKIETA"
        assert constraint.name == "B_ANKIETA_B_AUDYT_FK"
        assert constraint.constraint_type == "FK"
        assert constraint.columns == ["ID_FK_B_AUDYT"]
        assert constraint.ref_table == "B_AUDYT"
        assert constraint.ref_columns == ["ID_PK_B_AUDYT"]

    def test_unique_constraint_via_alter(self):
        """ALTER TABLE z UNIQUE — parsuje jako constraint UQ."""
        sql = '''ALTER TABLE "T" ADD CONSTRAINT "T_UQ" UNIQUE ("A", "B")'''
        result = parse_alter_table_fk(sql)
        assert result is not None
        _, c = result
        assert c.constraint_type == "UQ"


class TestParseCreateIndex:
    def test_unique_index(self):
        sql = 'CREATE UNIQUE INDEX "B_AUDYT_PK" ON "B_AUDYT" ("ID_PK_B_AUDYT")'
        idx = parse_create_index(sql)
        assert idx is not None
        assert idx.name == "B_AUDYT_PK"
        assert idx.table_name == "B_AUDYT"
        assert idx.columns == ["ID_PK_B_AUDYT"]
        assert idx.unique is True

    def test_regular_index(self):
        sql = 'CREATE INDEX "B_AK_IDX1" ON "B_AUDYT_KONTROLA" ("ID_FK_B_AUDYT")'
        idx = parse_create_index(sql)
        assert idx.unique is False

    def test_composite_index(self):
        sql = 'CREATE INDEX "IDX" ON "T" ("A", "B")'
        idx = parse_create_index(sql)
        assert idx.columns == ["A", "B"]

    def test_malformed_index_returns_none(self):
        """Niekompletny CREATE INDEX — brak kolumn."""
        sql = 'CREATE UNIQUE INDEX "SYS_IL0000082378C00005$$" ON "B_SL_C_PYTANIE" ('
        idx = parse_create_index(sql)
        assert idx is None


class TestParseCommentOn:
    def test_table_comment(self):
        sql = """COMMENT ON TABLE "B_AUDYT" IS 'Tabela audytow.'"""
        result = parse_comment_on(sql)
        assert result is not None
        obj_type, obj_name, col_name, text = result
        assert obj_type == "TABLE"
        assert obj_name == "B_AUDYT"
        assert col_name is None
        assert text == "Tabela audytow."

    def test_column_comment(self):
        sql = """COMMENT ON COLUMN "B_AUDYT"."STATUS_AUDYTU" IS 'Status audytu: Otwarty=edycja'"""
        result = parse_comment_on(sql)
        assert result is not None
        obj_type, obj_name, col_name, text = result
        assert obj_type == "COLUMN"
        assert obj_name == "B_AUDYT"
        assert col_name == "STATUS_AUDYTU"
        assert text == "Status audytu: Otwarty=edycja"

    def test_multiline_comment(self):
        """Komentarz z wieloliniowym SQL wewnątrz."""
        sql = """COMMENT ON TABLE "B_KONTROLA" IS 'WITH k AS (\nSELECT a FROM b\n)'"""
        result = parse_comment_on(sql)
        assert result is not None
        _, _, _, text = result
        assert "WITH k AS" in text


class TestParseCreateSequence:
    def test_sequence(self):
        sql = '''CREATE SEQUENCE "DAW_SEQ_B_C_ANAKIETA_PK"
                 MINVALUE 0 MAXVALUE 9999999 INCREMENT BY 1
                 START WITH 1203 NOCACHE NOORDER NOCYCLE'''
        seq = parse_create_sequence(sql)
        assert seq is not None
        assert seq.name == "DAW_SEQ_B_C_ANAKIETA_PK"
        assert seq.start_with == "1203"
        assert seq.increment_by == "1"
        assert seq.min_value == "0"
