---
# ====== Application: SKW_2_APEX =============================
id: 160
identification: 
  name: SKW_2_APEX
  alias: START338
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: ADFS Authentication Scheme # 40458398296031578

authorization: 
  authorization-scheme: Must Not Be Public User
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: DAW

globalization: 
  primary-language: Polish (pl)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: 'WORKSPACE #OWNER#'

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 100 Push Notifications Credentials # 29483363749875101

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--classic
  list-position: Side
  list: Navigation Menu # 52550476058029660

navigation-bar: 
  implementation: List
  list: Navigation Bar # 52834303076029317
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 8941380532190

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 273343216679699555
  identification: 
    name: APP_NAME

  value: 
    static-value: SKW_2_APEX

- # ====== Substitution: APP_COPYRIGHT =========================
  id: 273343216679699554
  identification: 
    name: APP_COPYRIGHT

  value: 
    static-value: Empowered by 🦄 Innovation Lab

component-settings: 
- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 1462713638043284
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 115213198

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 1476143065043281
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 115213205

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 1489628972043280
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 115213206

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 1504929648043274
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 115213218

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 37319745457119673
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 8772782069192

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 52546739235029671
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 52546993138029669
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 52547279927029669
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 52547580654029669
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 52547853219029669
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_IR ========================
  id: 52548224552029669
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 52548453619029668
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 52548829663029668
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 52549058782029668
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 1

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 52840395438029246
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 1

  configuration: 
    build-option: 'Feature: Feedback' # 52836960903029292

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 52840743174029244
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 52866390

  configuration: 
    build-option: 'Feature: Access Control' # 52836843194029292

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

